Mil mag fix
Eclipse-Station/NEV-Northern-Light pull request #1450
Opened 2021-03-30 10:43 UTC by MciReloaded

## About The Pull Request

Allows the users of Military Magboots to toggle them on and off, as requesting in Issue https://github.com/Eclipse-Station/NEV-Northern-Light/issues/452
## Why It's Good For The Game

Why should they have to have their magboots on all the time?
## Changelog
:cl:
fix: Allows Mercenaries to toggle their magboots on and off.
/:cl:

2021-04-01 17:57 UTC, drexample commented on code/modules/clothing/shoes/magboots.dm
> +	magpulse = 0
Do not use numbers for booleans

2021-04-01 17:57 UTC, drexample requested changes
Do not use numbers for booleans

2021-04-10 01:42 UTC, EvilJackCarver commented
Can you please use the [magic words](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) so that the issue is linked and will close automatically if this is merged?

2021-04-10 07:56 UTC, MciReloaded commented on code/modules/clothing/shoes/magboots.dm
> +	magpulse = 0
Hey it's what other things used but ye I can fix thaht

2021-04-12 14:03 UTC, EvilJackCarver approved these changes

2021-04-12 14:31 UTC, MciReloaded commented
I mean, it fixes #452

2021-04-17 14:06 UTC, merged