Eris Upstream Merge Part 27: Nestor Remembers He Has A Server (Also FBPs and Synths are fully in)
Eclipse-Station/NEV-Northern-Light pull request #1479
Opened 2021-05-06 01:29 UTC by drexample

## About The Pull Request

A big fukken Eris upstream merge + FBP/Synth inclusion

## Why It's Good For The Game

just trust me bro

## Changelog
:cl:
tweak: UPSTREAM MERGE BAYBEEEEE
/:cl:

2021-05-06 04:20 UTC, EvilJackCarver commented
I'm going to go ahead and flag the don't-merge on this until I finish reviewing it. This is a LOT of files to thumb through.

2021-05-06 04:47 UTC, EvilJackCarver requested changes
Gonna pump the brakes on reviewing for now. Here's what I've turned up so far.

2021-05-06 04:47 UTC, EvilJackCarver commented on code/controllers/subsystems/tickets/tickets.dm
> +	var/response_phrases = list("Thanks" = "Thanks, have a Paradise day!",
Did they pull this from Paradise and not change the text?

2021-05-06 04:47 UTC, EvilJackCarver commented on code/controllers/subsystems/tickets/tickets.dm
> +		"IC Issue" = "This is an In Character (IC) issue and will not be handled by admins. You could speak to Security, Internal Affairs, a Departmental Head, Nanotrasen Representetive, or any other relev
Typo in "Representative"

2021-05-06 04:47 UTC, EvilJackCarver commented on code/game/jobs/department.dm
> +	funding_type = FUNDING_NONE //The church on eris has no external funding. This further reinforces the theory that everyone on the CEV Eris is a reject of their factions
Are we sure we want to throw the Church's budget to the fire like this?

2021-05-06 04:47 UTC, EvilJackCarver commented on code/game/jobs/job/security.dm
> +	also_known_languages = list(LANGUAGE_CYRILLIC = 60, LANGUAGE_SERBIAN = 60, LANGUAGE_NEOHONGO = 100)
It'd be better to combine them into the first one or you'll lose the chance to know German.

2021-05-07 06:07 UTC, EvilJackCarver requested changes
Still not finished thumbing through the changes, but got a load more for ya.

2021-05-07 06:07 UTC, EvilJackCarver commented on code/modules/projectiles/guns/projectile/automatic/ak47.dm
> +			This cheap copy looks as tacticool as possible. Emulating the IH PD rifle in most ways, even the the fixed skeleton stock looks the same."
Ironhammer reference

2021-05-07 06:07 UTC, EvilJackCarver commented on code/modules/projectiles/guns/projectile/automatic/ak47.dm
> +			This rifle is from the Frozen Star's Planetary Defence line. Painted in IH blue and black, with a folding stock so it can be stored compactly for years without use."
Ironhammer reference

2021-05-07 06:07 UTC, EvilJackCarver commented on code/modules/projectiles/guns/projectile/automatic/motherfucker.dm
> +	desc = "A 6 barrel, pump action carbine, shakes like the devil. but will turn anything in a 90º from you in swiss cheese."
Consider rewriting the final part of the description to ..."but will turn anything inside a 90° cone in front of you into Swiss cheese"

2021-05-07 06:07 UTC, EvilJackCarver commented on code/modules/projectiles/guns/projectile/boltgun.dm
> +	desc = "A handmade bolt action rifle, made from junk. and some spare parts."
..."made from junk and some spare parts."

2021-05-07 06:07 UTC, EvilJackCarver commented on code/modules/projectiles/guns/projectile/revolver/handmade.dm
> +	desc = "Handmade revolver, made from gun parts. and some duct tap, will it even hold up?"
Consider rewriting to "A handmade revolver, made from gun parts and some duct tape. Will it even hold up?"

2021-05-07 06:07 UTC, EvilJackCarver commented on code/modules/projectiles/guns/projectile/sniper.dm
> +	desc = "A portable anti-armour rifle, fitted with a night-vision scope, it was originally designed for use against armoured exosuits. It is capable of punching through windows and non-reinforced wal
UK-ENG variant spelling

2021-05-08 00:34 UTC, EvilJackCarver commented on code/modules/research/xenoarchaeology/tools/anomaly_suit.dm
> +	desc = "A moebius branded violet voidsuit that is capable of protecting its user against most hostile environment conditions, including anomalous particles. Integrated self-diagnostics system not in
Moebius reference

2021-05-08 00:38 UTC, EvilJackCarver commented on maps/CEVEris/overmap-eris.dm
> +	name_stages = list("CEV Eris", "unknown vessel", "unknown spatial phenomenon")
CEV Eris mention

2021-05-08 00:40 UTC, EvilJackCarver commented on maps/submaps/planetary_ruins/ec_old_crash/ec_old_crash.dm
> +	I am Lieutenant Hao Ru, captain of [shipname] of the Hansa Trade Union. I will be joining my crew in cryo now.<br>
Metro 2033 reference, if we removed the one above

2021-05-08 00:49 UTC, EvilJackCarver commented
As a note (and because I want to separate it from the review), the changes to the icon code make me feel that it should be tested before merge, especially with reference to the modular files.

2021-06-01 14:08 UTC, EvilJackCarver requested changes
If you're reading the cliffnotes version on Discord, I'd recommend you open it up in your browser. I've probably edited it a few times since it got posted by the bot.

The short version is - we do plan to merge this. We're just busy.

The long version? Well...

I've heard a few people wondering about the state of this PR. It's not in limbo - we *are* planning to merge it at some point soon. However -

* I made a request to Nestor that he not work on this before he finished up the dispatcher, as I really wasn't up for fixing a fourth merge conflict - Nestor has agreed to that (and it's much appreciated).
* I cannot finish up the dispatcher myself, as I lack the required knowledge, experience, and a suitable testing environment for the dispatcher's webhook code.
* Nestor has been busy in real life with real life things (like uni), which has been keeping him from being able to work on the dispatcher.
* I'm the one blocking this PR from being merged, as there are unresolved issues, plus I would at least like to get Nestor's opinion on whether we want to throw away the entirety of the Church's budget ([see here](https://github.com/Eclipse-Station/NEV-Northern-Light/pull/1479#discussion_r627072091)).
* I would make a majority of the fixes myself, but I'm dealing with a bad bout of depression myself at the moment and haven't had the time nor the energy to work on it. Plus, I'm a lazy mike-foxtrot outside of the depression bit, anyway.

This *will be* merged in due time, don't worry - we're just busy with other things at the moment.

2021-06-04 07:18 UTC, benj8560 commented
was testing the church stuff for this PR and honestly even tho I love the new holiness system it feels like it lacks much impact. I var edited myself to full and charge times where still rather useless. Perhaps would be better if oblisks had considerably faster charge boost and maybe even give  cruciforms a lot more capacity. Also plasable holiness is just not working as intended since I seen almost no difference from the start charge speed and upgraded. This was awhile ago so could be these issues already got addressed. I told some other players about it when I was testing it and they seemed equally concerned about how bad it was.

2021-06-07 00:11 UTC, drexample commented on code/controllers/subsystems/tickets/tickets.dm
> +	var/response_phrases = list("Thanks" = "Thanks, have a Paradise day!",
yes

2021-06-07 00:14 UTC, drexample commented on code/game/jobs/department.dm
> +	funding_type = FUNDING_NONE //The church on eris has no external funding. This further reinforces the theory that everyone on the CEV Eris is a reject of their factions
We had intents on introducing more scarcity and ship is pretty deep away from any centralized banking, so let's see how that workks.

2021-06-07 00:15 UTC, drexample commented on code/modules/admin/bluespacetech.dm
> +	desc = "An ID straight from Hansa. This one looks as though its very existence is a trade secret."
Hansa sector is not a Metro reference.

2021-06-07 00:15 UTC, drexample commented on code/modules/admin/bluespacetech.dm
> +	desc = "An ID straight from Hansa. This one looks as though its very existence is a trade secret."
It's an eris lore "faction"

2021-06-07 00:19 UTC, drexample commented on code/modules/clothing/suits/miscellaneous.dm
> +	desc = "A sturdy, rigged Scavenger armor. strong and sturdy as most vests. made fully from junk."
copypaste issue, probably

2021-06-07 00:22 UTC, drexample commented on code/modules/long_range_scanner/long_range_scanner.dm
> +					logstring += "Shield powered down"
//This proc keeps an internal log of shield impacts, activations, deactivations, and a vague log of config changes

2021-06-07 01:19 UTC, EvilJackCarver commented on code/game/jobs/department.dm
> +	funding_type = FUNDING_NONE //The church on eris has no external funding. This further reinforces the theory that everyone on the CEV Eris is a reject of their factions
Alright, then.

2021-06-07 01:20 UTC, EvilJackCarver commented on code/game/jobs/job/security.dm
> +	also_known_languages = list(LANGUAGE_CYRILLIC = 60, LANGUAGE_SERBIAN = 60, LANGUAGE_NEOHONGO = 100)
There's four other entries in that file that suffer with the same problem, but I'll get 'em taken care of here in a few.

2021-06-07 01:30 UTC, EvilJackCarver approved these changes
Everything looks OK from my end. Just make sure the checks pass before you merge it.

I'll be releasing the DNM flag momentarily.

2021-06-07 02:33 UTC, merged