Upstream merge + a couple bugfixes [URGENT OPTIMIZATIONS]
Eclipse-Station/NEV-Northern-Light pull request #1499
Opened 2021-06-27 22:46 UTC by drexample

## About The Pull Request

Brings us up to date with Eris and fixes a little performance issue

## Why It's Good For The Game

Lags less and more content

## Changelog
:cl:
fix: Upstream merge and performance update!
/:cl:

2021-06-27 23:30 UTC, EvilJackCarver commented on code/__DEFINES/components.dm
> +#define COMSIG_ITEM_DROPPED	"item_dropped"					//from  /obj/item/weapon/tool/attackby(): Called to remove an upgrade
You moved the comment down a line

2021-06-27 23:32 UTC, drexample commented on code/__DEFINES/components.dm
> +#define COMSIG_ITEM_DROPPED	"item_dropped"					//from  /obj/item/weapon/tool/attackby(): Called to remove an upgrade
https://github.com/discordia-space/CEV-Eris/blob/fd64a4815da5aa0062b934786bf85eff4503a2af/code/__DEFINES/components.dm

Ain't me

2021-06-28 00:34 UTC, EvilJackCarver requested changes
Got the review done. Didn't look at maps or icon files, but here's everything else.

2021-06-28 00:34 UTC, EvilJackCarver commented on code/game/objects/items/weapons/storage/misc.dm
> +	desc = "Silvery plastic package, with the letters \"IHR\" pasted onto the front. Seems air tight, and vacuumed sealed. \
Ironhammer references

2021-06-28 00:34 UTC, EvilJackCarver commented on code/game/objects/items/weapons/tools/hammer.dm
> +	desc = "A modified sledgehammer produced by Frozen Star for Ironhammer forces. This tool can take down standard walls and if the user is strong enough, reinforced walls."
Ironhammer references

2021-06-28 00:34 UTC, EvilJackCarver commented on code/modules/clothing/head/armor.dm
> +	name = "insulated technomancer helmet"
Technomancer reference

2021-06-28 00:34 UTC, EvilJackCarver commented on code/modules/clothing/spacesuits/rig/suits/station.dm
> +	name = "technomancer suit control module"
Technomancer reference

2021-06-28 00:34 UTC, EvilJackCarver commented on code/modules/clothing/spacesuits/syndi.dm
> +	desc = "A clasic crimson helmet sporting clean lines and durable plating."
Classic (two S)

2021-06-28 00:34 UTC, EvilJackCarver commented on code/modules/clothing/spacesuits/syndi.dm
> +	desc = "A clasic crimson spacesuit sporting clean lines and durable plating."
Classic (two S)

2021-06-28 00:34 UTC, EvilJackCarver commented on code/modules/clothing/suits/armor.dm
> +	name = "insulated technomancer armor"
Technomancer reference

2021-06-28 00:34 UTC, EvilJackCarver commented on code/modules/dungeons/junk_tractor_beam.dm
> +		"IronHammer" = 3,
Ironhammer reference. Fixing this is gonna be a pain, so just be aware of this one.

2021-06-28 00:34 UTC, EvilJackCarver commented on code/modules/materials/material_sheets.dm
> +	desc = "This sheet is special plasma-glass alloy designed to withstand large temperatures"
Reference to plasma (versus phoron)

2021-06-28 00:34 UTC, EvilJackCarver commented on code/modules/materials/material_sheets.dm
> +	desc = "This sheet is special plasma-glass alloy designed to withstand large temperatures. It is reinforced with few rods."
Reference to plasma

2021-06-28 00:34 UTC, EvilJackCarver commented on code/modules/mob/living/simple_animal/friendly/cat.dm
> +/mob/living/simple_animal/cat/runtime
Ambiguous mob define, see line 231

2021-06-28 00:34 UTC, EvilJackCarver commented on code/modules/mob/living/simple_animal/hostile/syndicate.dm
> +	health -= 60*severity
Inconsistent behaviour - lower EMP `severity` numbers are more severe.

2021-06-28 00:34 UTC, EvilJackCarver commented on code/modules/projectiles/guns/energy/stun.dm
> +	desc = "Also know as stunrevolver. A Moebius copy of the older and less precise Nanotrasen solution for non-lethal takedowns. This gun has smaller capacity in exchange for S-cells use."
Moebius reference

2021-06-28 00:34 UTC, EvilJackCarver commented on code/modules/projectiles/guns/mods/research_mods.dm
>  	name = "Moebius \"Atomik\" isotope diffuser"
Moebius reference

2021-06-28 00:34 UTC, EvilJackCarver commented on code/modules/projectiles/guns/projectile/automatic/c20r.dm
> +	desc = "The C-20M is a Moebius copy of the famous C-20r, a lightweight and robust bullpup SMG of ancient design. \
Moebius reference

2021-06-28 00:34 UTC, EvilJackCarver commented on code/modules/tips_and_tricks/gameplay.dm
> +    tipText = "Did you know you can dismantle guns by using a wrench on them with harm intent ? Dismantling guns gives you gun parts."
Please remove the space before the question mark

2021-06-28 00:36 UTC, EvilJackCarver commented on code/modules/mob/living/carbon/human/update_icons.dm
> +			// Eclipse edit start - Gendered icon_overrides
Misleading comment

2021-06-28 00:45 UTC, drexample commented on code/modules/mob/living/simple_animal/friendly/cat.dm
> +/mob/living/simple_animal/cat/runtime
It's a cat that spawns whenever a runtime happens. It's not actually ambiguous.

2021-06-28 00:46 UTC, drexample commented on code/modules/dungeons/junk_tractor_beam.dm
> +		"IronHammer" = 3,
affinities are purely internal, so not a problem

2021-06-28 00:51 UTC, EvilJackCarver commented on code/modules/mob/living/simple_animal/friendly/cat.dm
> +/mob/living/simple_animal/cat/runtime
I'm talking about the define, not the name or behaviour. 

Runtime the Cat is `/mob/living/simple_animal/cat/fluff/Runtime`, and Dusty is `/mob/living/simple_animal/cat/runtime` - the only difference aside from case being the `/fluff/` part of the define.

2021-06-28 00:52 UTC, EvilJackCarver commented on code/game/machinery/alarm.dm
> +	if(world.time - last_hive_check > 150) //Checks every 15 seconds
Resolved through DMs

2021-06-28 00:53 UTC, EvilJackCarver commented on code/modules/dungeons/junk_tractor_beam.dm
> +		"IronHammer" = 3,
Looked like something read the affinities down farther below, which is why I brought it up.

2021-06-28 01:02 UTC, EvilJackCarver commented
Once the review's addressed, you're cleared to speedmerge after testing.

2021-06-28 01:16 UTC, EvilJackCarver approved these changes

2021-06-28 01:17 UTC, merged