Lore Fix
Eclipse-Station/NEV-Northern-Light pull request #1523
Opened 2021-07-27 23:35 UTC by Valanthe500

## About The Pull Request
Removed mention of Neotheology on the Holy Light Perk, Mekhane Voidsuit
Removed mention of Cobalt from many Aegis items/information

## Why It's Good For The Game
More Lore Compliance, yay!

## Changelog
:cl:
del: Removed references to Neotheology
del: removed references to Cobalt
/:cl:

2021-07-28 01:23 UTC, EvilJackCarver requested changes

2021-07-28 01:23 UTC, EvilJackCarver commented on code/datums/autolathe/biomatter.dm
> +	name = "Mekhanite Voidsuit"
Please use \improper so it doesn't say "This is Mekhanite Voidsuit"

2021-07-31 02:31 UTC, Valanthe500 commented on code/datums/autolathe/biomatter.dm
> +	name = "Mekhanite Voidsuit"
Done.

2021-07-31 02:32 UTC, EvilJackCarver approved these changes

2021-07-31 02:32 UTC, merged