Softening the Autolathe Nerf
Eclipse-Station/NEV-Northern-Light pull request #1524
Opened 2021-07-28 19:19 UTC by Sly9sky

## About The Pull Request
Autolathes will no longer print ammo magazines that are less than full. They also are able to have their print quality restored with very-high-quality manipulators installed.

## Why It's Good For The Game
Autolathes printing ammo magazines that are less than full did not entirely seem sensible to the point of nerfing their print quality, it did not make sense that less ammunition would be printed and cost the same amount of materials. 
I also desired to give another small way of restoring print quality to an autolathe such that players do not have to entirely depend on Lazarus to rejuvenate their printed product, especially when they are not present.

## Changelog
:cl:
tweak: Autolathes will no longer print magazines that are less than full
tweak: Autolathes can have their print quality restored with very-high-quality parts
/:cl:

2021-07-28 19:21 UTC, Sly9sky commented
Currently changing my code to line up with the up-to-date code (mainly around qdel and content/stored_ammo), as I worked with the original autolathe nerf PR on Eris that came before optimizations.

2021-07-29 04:33 UTC, EvilJackCarver approved these changes

2021-07-30 16:49 UTC, EvilJackCarver requested changes
Hey, I've gotta revoke the approval, just double-checked something with mine and that reminded me I never checked to see if you flagged your edits.

Please flag your edits in a comment (e.g. `//Eclipse edit`) so we can see that we've edited it should it get overwritten by an upstream merge - if you don't, and someone else changes the same things, it'll get overwritten.

2021-07-30 20:22 UTC, Sly9sky commented
> Hey, I've gotta revoke the approval, just double-checked something with mine and that reminded me I never checked to see if you flagged your edits.
> 
> Please flag your edits in a comment (e.g. `//Eclipse edit`) so we can see that we've edited it should it get overwritten by an upstream merge - if you don't, and someone else changes the same things, it'll get overwritten.
> 
> For more information, check [the Manual of Style](https://github.com/Eclipse-Station/NEV-Northern-Light/blob/master/CONTRIBUTING.md#editing-files-and-sprites-for-eclipse).

All Eclipse edits flagged.

2021-07-31 01:07 UTC, drexample commented on code/modules/scrap/oldificator.dm
> +	if(!low_quality_oldification) // Eclipse edit
Wait, why are you modifying oldificator?

2021-07-31 01:32 UTC, Sly9sky commented on code/modules/scrap/oldificator.dm
> +	if(!low_quality_oldification) // Eclipse edit
This change ensures that autolathes don't print less-than-full ammo. It doesn't mess with the part of it that oldifies maintenance ammo though, those will still spawn as usually less-than-full

2021-08-06 02:18 UTC, drexample approved these changes

2021-08-06 02:48 UTC, EvilJackCarver reviewed
Once you fix what Nestor needs, I don't see any reason this can't be merged.

2021-08-06 02:51 UTC, Sly9sky commented on code/modules/scrap/oldificator.dm
> +			QDEL_NULL(trash_mod)
Gotcha, doing so now

2021-08-06 02:53 UTC, Sly9sky commented
> Once you fix what Nestor needs, I don't see any reason this can't be merged.

Done

2021-08-06 02:54 UTC, EvilJackCarver approved these changes

2021-08-07 02:00 UTC, merged