Vine spawn restrictions
Eclipse-Station/NEV-Northern-Light pull request #1546
Opened 2021-09-25 03:50 UTC by Sly9sky

## About The Pull Request

As a first part of improvements I've wanted to introduce to space vines, they shall no longer spawn or take burrows into maintenance to reduce the hardships of finding and destroying them.

## Why It's Good For The Game

Space vines are currently impossible to eliminate because they very often end up in maintenance and get a free base from which they can spread from forever.

With this PR, they will be barred from burrowing into or spawning in maintenance such that they can still be spread fairly quickly, but now crew can be expected to monitor crew areas to catch it spawning and having an AI can certainly help find where it is spreading.

Lastly, the only way they will be allowed to enter maintenance, as observed in testing, is to spread into it originating from a crew area.

## Changelog
:cl:
balance:  strange plants will no longer spawn or burrow into maintenance
/:cl:

2021-09-25 05:40 UTC, EvilJackCarver requested changes

2021-09-25 05:40 UTC, EvilJackCarver commented on code/modules/hydroponics/spreading/spacevines.dm
> +			qdel(src) //Eclipse Edit, disables starting off in maintenance
This will delete the atom that's calling the infestation proc, are you sure you want to do that? If so, it's going to need error-handling to prevent it deleting a floor if an edge case happens.

2021-09-25 15:21 UTC, Sly9sky commented on code/modules/hydroponics/spreading/spacevines.dm
> +			qdel(src) //Eclipse Edit, disables starting off in maintenance
For now I'm sure I wish to do it, as telling it to continue or break would still result in a spawn in maintenance.

Originally the code was supposed to look for crew areas to spawn in- to continue if an atom in maintenance was selected but this results in maintenance spawns anyway.

Unless there is a softer alternative I'm not yet aware of, I do wish to keep it as is. I'm willing to but I've not learned error-handling yet, and all tests I've conducted so far have not resulted in deletion of a floor.

2021-09-25 15:43 UTC, EvilJackCarver commented on code/modules/hydroponics/spreading/spacevines.dm
> +			qdel(src) //Eclipse Edit, disables starting off in maintenance
Very well. I don't like it, but I'll allow it.

2021-09-25 15:43 UTC, EvilJackCarver approved these changes

2021-09-25 15:57 UTC, Sly9sky commented on code/modules/hydroponics/spreading/spacevines.dm
> +			qdel(src) //Eclipse Edit, disables starting off in maintenance
> Very well. I don't like it, but I'll allow it.

As said, I'm willing to learn how to introduce error-handling

2021-09-25 16:14 UTC, Sly9sky commented
Currently testing this for possible softer alternatives, please don't merge this quite yet

2021-09-25 16:29 UTC, EvilJackCarver commented
I'm flagging don't-merge and MTestR on this. This PR deals with Nanako's code, which may be what's causing the spread to maintenance despite the code specifically forbidding that.

2021-09-25 17:26 UTC, Sly9sky commented
> I'm flagging don't-merge and MTestR on this. This PR deals with Nanako's code, specifically the strange implementation of a while-loop where a for-loop would theoretically suffice, which may be what's causing the spread to maintenance despite the code specifically forbidding that.

You're certainly right, a for loop works far better than a while loop. It's more stuff for me to be able to learn and I'm thankful for your input.

2021-09-26 04:16 UTC, EvilJackCarver approved these changes
Passes maintainer testing.

2021-09-29 11:36 UTC, merged