Valanthe bugfixing
Eclipse-Station/NEV-Northern-Light pull request #1564
Opened 2021-10-31 00:20 UTC by Valanthe500

## About The Pull Request
- Fixes #1521
--  fixes the Panzer Roach sprite, removing a stray pixel
- Corrects dozens of Eris lore mentions, removing references to Moebius, Neotheology, and Ironhammer. 
- Fixes #1560 
-- re-adds the biofabrics disk to the preacher's locker, and removes the exception from the Eye for the basic weapons disk.
- Partially fixes issue #1557 
-- fixed the textbox issue with Nanoword, it now uses a proper textbox. Report editor, per popular demand, is being left as is until a proper fix can be made.
- Adds the monitor key paper to the CSO's locker, as it currently doesn't spawn anywhere.

## Why It's Good For The Game
This is a pack of very small QoL fixes, none of these issues are game-breaking,  but the nanoword fix in particular has been a thorn in the side of paperwork using players for a long time, and the Eris lore is a personally pet peeve of mine.

## Changelog
:cl:
add: Added the monitor key paper to the CSO's locker
del: Removed Eris lore references
fix: fixed Nanoword displaying a single line textbox
fix: replaced biofabrics disk in preacher's locker and removed the exemption from the Eye for the melee weapons disk
/:cl:

2021-10-31 01:12 UTC, EvilJackCarver requested changes

2021-10-31 01:12 UTC, EvilJackCarver commented on code/game/objects/items/devices/radio/headset.dm
> +	name = "Aegis commander headset"
Need to have an `\improper` preceding the names of general items if the first letter is capital, otherwise the game will treat it as Proper Object and leave out the "a" or "the" preceding it in examine texts.

2021-10-31 01:12 UTC, EvilJackCarver commented on code/modules/modular_computers/file_system/programs/generic/wordprocessor.dm
> +		\\Eclipse Edits - Changed to match our lore.
Double-backslash preceding comment (should be double-forward-slash).

Double-backslashes are used to print a single backslash in a string; the first backslash escapes the second, causing the second to not escape the next word.

2021-10-31 01:35 UTC, Valanthe500 commented on code/game/objects/items/devices/radio/headset.dm
> +	name = "Aegis commander headset"
Added where appropriate

2021-10-31 01:35 UTC, Valanthe500 commented on code/modules/modular_computers/file_system/programs/generic/wordprocessor.dm
> +		\\Eclipse Edits - Changed to match our lore.
Corrected.

2021-10-31 01:37 UTC, EvilJackCarver commented on code/modules/modular_computers/file_system/programs/generic/wordprocessor.dm
> +		\\Eclipse Edits - Changed to match our lore.
Hm, that's weird, it's still syntax-highlighted. I'll have to take a look and see what's going on there.

2021-10-31 02:05 UTC, Valanthe500 commented on code/modules/modular_computers/file_system/programs/generic/wordprocessor.dm
> +		\\Eclipse Edits - Changed to match our lore.
I think I know why it's flipping out. I put the comment inside of a field that's printing, so the code is just printing that whole section in the chatbox and ignoring that its a comment. (comment was added as an afterthought before I pushed the commit. Should have caught that issue in testing but whoopsie)

Hopefully this change fixes it.

2021-10-31 02:06 UTC, EvilJackCarver approved these changes

2021-11-01 00:35 UTC, EvilJackCarver commented
Seems CI doesn't like that fix there. I'm gonna re-run the checks, but if that doesn't work, I'll run a manual CI check.

2021-11-01 00:42 UTC, EvilJackCarver approved these changes

2021-11-03 01:57 UTC, merged