Big Gunz  (WIP DO NOT MERGE)
Eclipse-Station/NEV-Northern-Light pull request #1584
Opened 2021-11-18 11:06 UTC by Valanthe500

## About The Pull Request
Adds "Paladin" and "Squire." Two new guns for the church, single shot laser weapons that trash their cells after firing. They're slow to fire, but hard hitting. Currently only available through a design disk through the Eye. This may be expanded later once a decision is reached regarding the Svallinn and Martyr.
- Squire is currently using a placeholder sprite until a proper one can be secured.
- New "dead cell" object has been added (with small and medium variants). This gives the new weapons a 'casing' that gets ejected along with some ash and sparks (careful around fuel leaks) when fired.

Went through *all* of the guns, tweaked spelling and grammar on descriptions. Also set all gun names to follow a consistent style. Most firearms on our server follow the style of "[Manufacturer's Initials] [Weapon Type] [Caliber] "[Name]"." So for example, a "FS HG .35 Auto "Colt M1911"" could be identified as a Frozen Star (FS) Handgun (HG) that used .35 Auto (.35 Auto) and was called the "Colt M1911." This makes disseminating the important information about the gun very simple and easy, however not all firearms followed this convention, and some did so inconsistently, especially some energy weapons. So I have gone through all of the firearms and made most of them follow this convention.
- Added manufacturer tags where appropriate, prototype or handmade firearms that aren't made by a corp don't get these.
- Changed "Excelsior" to "EX" to (slightly) obfuscate the communist connection and bring the naming in line with the others.
- Oberth Weapons are now labelled "OSDF" for "Oberth Strategic Defence Force." As they had several different acronyms prior
- Added either "S" "M" or "SC" to Energy weapons in the ammo type field to mark their cell type (Small, Medium, and Self Charging, respectively)
- Changed some weapon types to better reflect their purpose and be more consistent (A scoped, full-length, semi-auto laser rifle being called a carbine... really?)
 
Swapped the BIO resist for Acolyte/Custodian armour so Acolytes can do their job again.
- Bonus fix, because I happened to open the file for some other reason
- From our own wiki: "As an Acolyte, you have the armor and the equipment to operate the Bioreactor without succumbing to the instant death of the foul smell of the biomass. " 
- They do now with this change.

Adds the "Olympus" and "Serenity" for the BO, 
- These replace the Martin, Colt, and Sol placeholders they have now, giving them weapons unique to their role and station.
- The Serenity spawns with them out of cryo, giving them a self-defence weapon akin to  the Martin should things on the ship be interesting when they log in.
- Olympus is currently in their locker. Once the new map update is pushed, these will be moved to a more appropriate place. Most likely a showcase that can be accessed in emergencies.

## Why It's Good For The Game
The new weapons give Church players a weapon that is both unique to them, and useful for them. Currently the Svallinn and Martyr, as their 'entry level' weapons are very lackluster, and ditched as soon as something better can be found (sometimes earlier)

The gun tweaks make disseminating information easier for players, making it easier at a glance to tell what a particular gun might be useful for. And everyone loves spelling correction.

The BO guns have been a long time coming, They were planned even before we had the BO role, but getting sprites delayed the project considerably, and it got forgotten about until recently. Now the BO can have a weapon that feels like it belongs to them, rather than just a junky pistol anyone can buy from a vending machine.

## Changelog
:cl:
add: Added "Paladin" and "Squire" - two new guns for the church
add: Added "Olympus" and "Serenity" - two new guns for the BO
balance: Flipped Acolyte / Custodian armours' BIO resist so Acolytes can do their job once more.
spellcheck: fixed typos and grammar in gun descriptions
spellcheck: brought all guns into line with naming conventions.
/:cl:

2021-11-18 12:11 UTC, EvilJackCarver commented
Let me know when it's ready for review.

2021-11-27 02:43 UTC, Valanthe500 commented
In order to get this moving I've commented out the Squire from the build disk and blacklisted it while we're waiting on the sprite. This PR is otherwise finished and ready for review.

2021-11-27 03:11 UTC, EvilJackCarver requested changes

2021-11-27 03:11 UTC, EvilJackCarver commented on code/modules/projectiles/guns/projectile/pistol/selfload.dm
> +	desc = "An old design pistol popular among space communists. Small and easily concealable. Uses .35 Auto rounds."
Unflagged edit, but "An old design pistol popular among space communists" doesn't read too well (particularly at the start).

2021-11-27 03:11 UTC, EvilJackCarver commented on zzz_modular_eclipse/code/modules/projectiles/guns/energy/paladin.dm
> +	charge_cost = 10000 //No matter what cell you put in, it's gonna fry it.
It might be a good idea to add a zero to this. I don't know if the larger cell slot upgrade for tools also works for guns, but if it does, that would mean you could theoretically get more than one shot with a large cell.

2021-11-27 03:11 UTC, EvilJackCarver commented on zzz_modular_eclipse/code/modules/projectiles/guns/energy/serenity.dm
> +	desc = "This self-charging laser pistol was originally developed as a custom sidearm for a now deceased free trader captain. NanoTrasen reverse-engineered the design, and put the “Serenity” into pro
"[...] for a *now-deceased Free Trader* captain. [...]"

2021-11-27 03:11 UTC, EvilJackCarver commented on zzz_modular_eclipse/code/modules/projectiles/guns/energy/squire.dm
> +	desc = "The Mekhane Armoury \"Squire\" laser pistol is a cheap, easily produced sidearm issued to Mekhane disciples for self-defence. It is best used with Mekhane disposable cells, but can load any
* EN-UK variant spelling
* "[...] cheap, *easily-produced* sidearm [...]"

2021-11-27 03:11 UTC, EvilJackCarver commented on zzz_modular_eclipse/code/modules/projectiles/guns/energy/squire.dm
> +	suitable_cell = /obj/item/cell/small
See comment on the Paladin re: cell size upgrade and weapons.

2021-11-27 03:11 UTC, EvilJackCarver commented on zzz_modular_eclipse/code/modules/projectiles/guns/projectile/automatic/olympus.dm
> +	desc = "The Olympus was Initially set up as an alternative for wealthy planetary defense forces seeking a hard hitting yet controllable primary weapon for their forces. It proved to be an initial co
* "hard-hitting" (both cases)
* "It's" is possessive ("It is"), "Its" describes a property of the subject ("it has [a/an]")

2021-11-27 03:43 UTC, Valanthe500 commented on zzz_modular_eclipse/code/modules/projectiles/guns/energy/paladin.dm
> +	charge_cost = 10000 //No matter what cell you put in, it's gonna fry it.
The larger cell upgrade does not work on firearms, only tools. That was something I tested, however an extra zero probably couldn't hurt in case that gets changed at some point in the future.

2021-11-27 03:44 UTC, EvilJackCarver commented on zzz_modular_eclipse/code/modules/projectiles/guns/energy/paladin.dm
> +	charge_cost = 10000 //No matter what cell you put in, it's gonna fry it.
Ah, good. Works for me.

2021-11-27 03:48 UTC, Valanthe500 commented on code/game/objects/items/weapons/storage/pouches.dm
> +		/obj/item/gun/energy/laser/squire //Eclipse Edit - pistol for the pistol holster
There is another comment in this list a few lines up from mine (line 260), do you want me to remove that as well?

2021-11-27 03:49 UTC, EvilJackCarver commented on code/game/objects/items/weapons/storage/pouches.dm
> +		/obj/item/gun/energy/laser/squire //Eclipse Edit - pistol for the pistol holster
Probably for the best.

2021-11-27 03:54 UTC, Valanthe500 commented on zzz_modular_eclipse/code/modules/projectiles/guns/energy/squire.dm
> +	desc = "The Mekhane Armoury \"Squire\" laser pistol is a cheap, easily produced sidearm issued to Mekhane disciples for self-defence. It is best used with Mekhane disposable cells, but can load any
(It's the US who's the variant) but fiiine I'll change it.

2021-11-27 03:55 UTC, EvilJackCarver commented on zzz_modular_eclipse/code/modules/projectiles/guns/energy/squire.dm
> +	desc = "The Mekhane Armoury \"Squire\" laser pistol is a cheap, easily produced sidearm issued to Mekhane disciples for self-defence. It is best used with Mekhane disposable cells, but can load any
I prefer UK-variant spelling myself, but Nestor made a point to have everything US-variant back in ES13.

2021-11-27 03:56 UTC, Valanthe500 commented on zzz_modular_eclipse/code/modules/projectiles/guns/projectile/automatic/olympus.dm
> +	desc = "The Olympus was Initially set up as an alternative for wealthy planetary defense forces seeking a hard hitting yet controllable primary weapon for their forces. It proved to be an initial co
And this is why I should know better than to just copy-paste things others write for me.

2021-11-28 07:16 UTC, EvilJackCarver commented
Only thing we're waiting on is the variant spelling.

2021-11-28 10:29 UTC, Valanthe500 commented on zzz_modular_eclipse/code/modules/projectiles/guns/energy/squire.dm
> +	desc = "The Mekhane Armoury \"Squire\" laser pistol is a cheap, easily produced sidearm issued to Mekhane disciples for self-defence. It is best used with Mekhane disposable cells, but can load any
Done, changed both the Paladin and Squire.

2021-11-28 10:38 UTC, EvilJackCarver commented on zzz_modular_eclipse/code/modules/projectiles/guns/energy/squire.dm
> +	desc = "The Mekhane Armoury \"Squire\" laser pistol is a cheap, easily produced sidearm issued to Mekhane disciples for self-defence. It is best used with Mekhane disposable cells, but can load any
"self-defense", and we'll be good to merge.

2021-11-28 10:47 UTC, Valanthe500 commented on zzz_modular_eclipse/code/modules/projectiles/guns/energy/squire.dm
> +	desc = "The Mekhane Armoury \"Squire\" laser pistol is a cheap, easily produced sidearm issued to Mekhane disciples for self-defence. It is best used with Mekhane disposable cells, but can load any
I want you to know this causes me physical pain.

2021-11-28 10:49 UTC, EvilJackCarver commented on zzz_modular_eclipse/code/modules/projectiles/guns/energy/squire.dm
> +	desc = "The Mekhane Armoury \"Squire\" laser pistol is a cheap, easily produced sidearm issued to Mekhane disciples for self-defence. It is best used with Mekhane disposable cells, but can load any
It's not just you. It's me as well. I prefer Commonwealth spelling over American spelling (colour, jewellery, centre, etc.)

2021-11-28 10:58 UTC, Valanthe500 commented on zzz_modular_eclipse/code/modules/projectiles/guns/energy/squire.dm
> +	desc = "The Mekhane Armoury \"Squire\" laser pistol is a cheap, easily produced sidearm issued to Mekhane disciples for self-defence. It is best used with Mekhane disposable cells, but can load any
Hopefully that's the last one.

2021-11-28 14:51 UTC, EvilJackCarver approved these changes

2021-12-06 15:36 UTC, merged