Valanthe bugfixing
Eclipse-Station/NEV-Northern-Light pull request #1586
Opened 2021-11-21 09:29 UTC by Valanthe500

## About The Pull Request
Squashing bugs like I'm a gosh-dang Starship Trooper
- Fixes #1484 edited the existing check just before handle_flee_target() as messing with the life() proc directly looks like it's liable to go poorly.
- Fixes #314 The issue is isolated solely to items that spawn in the hand, I've fixed the issue by moving those items into the backpack contents. This has the added benefit of reducing the likelihood that you'll need to pick up things from the ground when you leave cryo, as now it will only dump items if your backpack is full.
- Fixes #395 Added a return statement to stop the main menu from reappearing above the manifest in the lobby.
-  Fixes #348 Made Surgical Aprons cover the arms to prevent blood from spraying your jumpsuit if you mess up in surgery. This isn't an ideal solution,  as the sprite for the surgical apron doesn't cover the arms, but aside from refactoring the way blood-splatter works, I'm not sure what else we can do to resolve this. It may be possible in the future to get a new sprite for surgical aprons that shows them covering the arms.
- Fixes #356 Uncommented the visible warning, so now there is a dialogue when you begin to cuff someone.
- Fixes #1568 Added visible message when trying to use an empty trauma kit that warns if the kit is empty.

## Why It's Good For The Game
Squishing bugs is very cathartic, both for me, and the players. One by one I am slowly chipping away at the mountain of issues in our code base.

## Changelog
:cl:
fix: fixed Bones hissing while dead
fix: fixed items not spawning with players in the dorms
fix: fixed the main menu appearing over the manifest in the main menu
fix: fixed jumpsuits getting bloodied during surgery while wearing surgical apron
fix: fixed handcuffs not giving a visible warning when you start to use them
fix: Trauma kits will now tell you when they're empty
/:cl:

2021-11-21 10:16 UTC, EvilJackCarver requested changes
Flag your edits, please

2021-11-21 10:39 UTC, Valanthe500 commented
> Flag your edits, please

My bad, fixed.

2021-11-21 10:40 UTC, EvilJackCarver approved these changes

2021-11-24 16:17 UTC, EvilJackCarver approved these changes

2021-11-24 16:23 UTC, merged