Upstream megamerge
Eclipse-Station/NEV-Northern-Light pull request #1618
Opened 2022-02-16 23:37 UTC by drexample

## About The Pull Request

Merges with upstream and brings a lot of neat stuff. Also a couple of small map fixes.

## Why It's Good For The Game

It's good. 

Closes #1617
Closes #1616 
Closes #1615 

## Changelog
:cl:
add: Upstream merge!
/:cl:

2022-02-17 02:39 UTC, EvilJackCarver requested changes
I genuinely do not have the energy to completely go through everything in one day. This is going to take a while, but here's what I've got so far.

2022-02-17 02:39 UTC, EvilJackCarver commented on code/controllers/subsystems/economy.dm
> +	command_announcement.Announce("Hourly crew wages have been paid, please check your email for details. In total the crew of CEV Eris have earned [total_paid] credits, including [paid_external] credit
CEV Eris regression

2022-02-17 02:39 UTC, EvilJackCarver commented on code/controllers/subsystems/economy.dm
> +			transfer_funds(EA, A, "Payroll Funding", "CEV Eris payroll system", amount_to_pay)
CEV Eris regression

2022-02-17 02:39 UTC, EvilJackCarver commented on code/controllers/subsystems/economy.dm
> +				transfer_funds(EA, A, "Payroll Funding", "CEV Eris payroll system", amount_to_pay)
CEV Eris regression

2022-02-17 02:39 UTC, EvilJackCarver commented on code/__DEFINES/economy.dm
> -#define FUNDING_EXTERNAL	2	//Funded from an external source, like moebius corp. Money is technically created out of nothing
I hope you know what you are doing.

2022-02-17 02:39 UTC, EvilJackCarver commented on code/datums/ai_law_sets.dm
> +	src.add_inherent_law("Preserve: Do not allow unauthorized personnel to tamper with your equipment. Only Captain, Moebius Expedition Overseer, First Officer and Technomancer Exultant are authorized t
Moebuis and Technomancer references

2022-02-18 02:13 UTC, EvilJackCarver requested changes
433 of 1099.

2022-02-19 16:37 UTC, EvilJackCarver requested changes
300 to go

2022-02-19 16:37 UTC, EvilJackCarver commented on code/modules/clothing/suits/armor.dm
> +	name = "Moebius paramedic armor"
Moebius reference

2022-02-19 16:37 UTC, EvilJackCarver commented on code/modules/clothing/under/jobs/civilian.dm
> +	desc = "An apron which is given only to the most <b>hardcore</b> chefs in space."
Would probably read better as "An apron, given only to ..."

2022-02-19 16:37 UTC, EvilJackCarver commented on code/modules/clothing/under/jobs/engineering.dm
> +	desc = "A orange jumpsuit that great for industrial work."
"An orange jumpsuit ..."

2022-02-19 16:37 UTC, EvilJackCarver commented on code/modules/core_implant/cruciform/machinery/cruciformforge.dm
> +	var/tmp/obj/effect/flick_light_overlay/image_load
Another flicker → flick_light regression, this one'll probably runtime if it's ever called

2022-02-19 16:37 UTC, EvilJackCarver commented on code/modules/dungeons/teleporter.dm
> +	var/flick_lighting = 0
Flicker → flick_light regressions all throughout this file (^F for "flick_lighting")

2022-02-19 16:37 UTC, EvilJackCarver commented on code/modules/hivemind/machines.dm
> +			to_chat(H, SPAN_NOTICE("Reality flick_lights for a second, but you manage to focus!"))
Remind me later to grumble at you for allowing someone to `sed s/flicker/flick_light/g` and allowing that to get through code review.

2022-02-19 16:37 UTC, EvilJackCarver commented on code/modules/integrated_electronics/core/assemblies.dm
> +				var/saved = "On circuit printers cloning enabled, you may use the code below to clone the circuit:<br><br><code>[SScircuit.save_electronic_assembly(src)]</code>"
This change breaks the sentence's grammar.

2022-02-19 16:37 UTC, EvilJackCarver commented on code/modules/integrated_electronics/core/assemblies.dm
> +			to_chat(user, SPAN_WARNING("[src]'s hatch is closed, so you can't fiddle the internal components."))
Another change that breaks the sentence's grammar.

2022-02-19 16:37 UTC, EvilJackCarver commented on code/modules/integrated_electronics/core/assemblies.dm
> +			to_chat(user, SPAN_WARNING("[src]'s hatch is closed, so you can't fiddle the internal components."))
More grammar-breaking changes.

2022-02-19 16:37 UTC, EvilJackCarver commented on code/modules/mob/living/carbon/human/human.dm
> +	"NeoTheology Preacher" = "Reverend",\
NeoTheo reference

2022-02-19 16:37 UTC, EvilJackCarver commented on code/modules/mob/living/carbon/slime/examine.dm
> +				msg += "It is flick_lighting gently with a little electrical activity.\n"
screaming

2022-02-19 16:37 UTC, EvilJackCarver commented on code/modules/mob/living/carbon/superior_animal/golem/types/plasma.dm
> +	desc = "A moving pile of rocks with plasma specks in it."
Phoron, not plasma

2022-02-19 16:37 UTC, EvilJackCarver commented on code/modules/mob/living/carbon/superior_animal/golem/types/plasma.dm
> +					visible_message(SPAN_DANGER("\The [src] explodes into a ball of burning palsma!"))
Phoron, and hilariously enough, it's also typo'ed.

2022-02-19 16:37 UTC, EvilJackCarver commented on code/modules/mob/living/carbon/superior_animal/roach/types/bluespace.dm
> +	desc = "This shimmering insectoid-like creature greatly resembles a giant cockroach. It flick_lights in and out of reality, as if it didn't really belong here."
screm

2022-02-19 16:37 UTC, EvilJackCarver commented on code/modules/mob/living/silicon/robot/drone/_drone.dm
> +	to_chat(user, SPAN_DANGER("You swipe the sequencer across [src]'s interface and watch its eyes flick_light."))
SCREM.

2022-02-19 16:37 UTC, EvilJackCarver commented on code/modules/modular_computers/computers/modular_computer/core.dm
> +		to_chat(user, "You emag \the [src]. Its screen flick_lights briefly.")
this is why you never do a global search and replace

2022-02-19 16:37 UTC, EvilJackCarver commented on code/modules/modular_computers/computers/modular_computer/hardware.dm
> +		to_chat(user, SPAN_DANGER("\The [src]'s screen freezes for a split second and flick_lights to black."))
it causes shenanigans like this

2022-02-19 16:37 UTC, EvilJackCarver commented on code/modules/modular_computers/computers/modular_computer/power.dm
> +		visible_message("<span class='danger'>\The [src]'s screen flick_lights briefly and then goes dark.</span>", range = 1)
and makes it really difficult to track down and undo

2022-02-19 16:37 UTC, EvilJackCarver commented on code/modules/modular_computers/computers/subtypes/dev_tablet.dm
> +	desc = "A small, portable microcomputer. This one has two extra screens and a Moebius Laboratories logo stamped on the back."
Moebius reference

2022-02-19 16:37 UTC, EvilJackCarver commented on code/modules/modular_computers/file_system/programs/generic/taxes.dm
> +		var/account_type = alert("Personal account have all basic functionality and cost [account_registration_fee] credits. Department account additionally can add other accounts to authomated payroll and
Pluralise "accounts"

2022-02-19 16:37 UTC, EvilJackCarver commented on code/modules/modular_computers/file_system/programs/generic/taxes.dm
> +	filedesc = "TaxQuickly 2565"
Year is in the future

2022-02-19 16:37 UTC, EvilJackCarver commented on code/modules/organs/surgery_helpers.dm
> +// flick_lights a pain message to the owner, if the body part can feel pain at all
screm

2022-02-19 16:37 UTC, EvilJackCarver commented on code/modules/power/apc.dm
> +	visible_message(SPAN_NOTICE("[src]'s screen flick_lights with warnings briefly!"))
screm

2022-02-19 16:37 UTC, EvilJackCarver commented on code/modules/power/lighting.dm
> +	var/flick_lighting = 0
screm

2022-02-19 16:37 UTC, EvilJackCarver commented on code/modules/power/lighting.dm
>  	spawn(0)
screm²

2022-02-19 16:37 UTC, EvilJackCarver commented on code/modules/power/lighting.dm
> +// ai attack - make lights flick_light, because why not
screm³

2022-02-20 02:32 UTC, EvilJackCarver requested changes
Finished thumbing through the files.

2022-02-20 02:32 UTC, EvilJackCarver commented on code/modules/projectiles/guns/projectile/automatic/c20r.dm
> +	desc = "A C20r SMG frame. The syndicate's bread and butter."
Reference to the Syndicate as a faction

2022-02-20 02:32 UTC, EvilJackCarver commented on code/modules/projectiles/guns/projectile/automatic/c20r.dm
> +	desc = "A C-20M SMG frame. The syndicate's bread and butter, reverse-engineered."
Reference to the Syndicate as a faction

2022-02-20 02:32 UTC, EvilJackCarver commented on code/modules/projectiles/guns/projectile/automatic/wintermute.dm
> +	desc = "A Wintermute assault rifle frame. The finest of the Ironhammer lineup."
Ironhammer reference

2022-02-20 02:32 UTC, EvilJackCarver commented on code/modules/projectiles/guns/projectile/pistol/selfload.dm
> +	desc = "Self-loading pistol of Syndicate design rebranded by Moebius Laboratories. Uses both standard and highcap .35 Auto mags."
Moebius reference

2022-02-20 02:32 UTC, EvilJackCarver commented on code/modules/reagents/reagent_containers/food/snacks.dm
> +	desc = "A piece human meat on a stick."
"A piece of human ..." would be more grammatically-correct.

2022-02-20 02:32 UTC, EvilJackCarver commented on code/modules/reagents/reagent_containers/food/snacks.dm
> +	name = "scaredy's private reserve beef jerky"
Probably best to leave it capitalised and add an `\improper` to it, since it is a brand name

2022-02-20 02:32 UTC, EvilJackCarver commented on code/modules/research/designs.dm
> +	sort_string = "VASAE"
Moebius references

2022-02-20 02:32 UTC, EvilJackCarver commented on code/modules/research/nodes/combat.dm
> +	desc = "Standard issue armor of moebius paramedic teams."
Moebius reference

2022-02-20 02:32 UTC, EvilJackCarver commented on code/modules/research/xenoarchaeology/artifact/artifact_replicator.dm
> +		[pick("swirls","flashes","whirrs","goes schwing","blinks","flick_lights","strobes","lights up")] on the \
flick_lights regex cock-up

2022-02-20 02:32 UTC, EvilJackCarver commented on code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_badfeeling.dm
> +		"The light seems to flick_light.",\
flick_light regex cock-up

2022-02-20 02:32 UTC, EvilJackCarver commented on code/modules/trade/datums/trade_stations_presets/1-common/caduceus.dm
> +		"MAV 'Caduceus'" = "Moebius Aid Vessel 'Caduceus': \"Hello there, we are from the Old Sol Republic. We will be leaving the system shortly but we can offer you medical supplies in the mean time.\"."
Reference to Moebius as a faction, though this one I'm less concerned about since it's not on the ship.

2022-02-20 02:32 UTC, EvilJackCarver commented on code/modules/trade/datums/trade_stations_presets/1-common/nt_cruisers.dm
> +		"NTV 'Faith'" = "NeoTheology Vessel 'Faith': \"The most holy purveyors of ecclesiarchic goods!\"",
Reference to NeoTheo as a faction, though again, less concerned about this one since it's off-ship.

2022-02-20 02:32 UTC, EvilJackCarver commented on code/modules/trade/datums/trade_stations_presets/2-uncommon/advmoe.dm
> +		"MTB 'Ningishzida'" = "Moebius Trade Beacon 'Ningishzida': Connection with the Moebius surplus network established."
Moebius as an off-ship faction

2022-02-20 02:32 UTC, EvilJackCarver commented on code/modules/trade/datums/trade_stations_presets/2-uncommon/nt_uncommon.dm
> +		"NTV 'Hope'" = "NeoTheology Vessel 'Hope': \"Reliable, blessed and sanctified goods for the correct price.\""
NeoTheo as an off-ship faction

2022-02-20 02:32 UTC, EvilJackCarver commented on code/modules/trade/datums/trade_stations_presets/3-rare/illegalbeacon.dm
> +		"Syndicate Gear" = list(
Reference to the Syndicate as an off-ship faction throughout the file

2022-02-20 02:32 UTC, EvilJackCarver commented on code/modules/trade/datums/trade_stations_presets/3-rare/monstertrapper.dm
> +		"EXT 'Armitage'" = "Exterminator 'Armitage': \"Greetings, Eris. We're in a bit of a rough spot at the moment. Got any traps to spare?\"",
Reference to the Eris as the ship's name

2022-02-20 02:32 UTC, EvilJackCarver commented on tools/hooks/install.bat
> -
It got deleted again

2022-02-25 23:04 UTC, drexample commented on code/modules/admin/holder2.dm
> +NOTE: It checks usr by default. Supply the "�" argument if you wish to check for a specific client/mob.
![image](https://user-images.githubusercontent.com/19371983/155814708-e91e18c9-14d6-45a4-b8ac-f85295ff036b.png)
Font thing

2022-02-25 23:05 UTC, drexample commented on code/modules/admin/holder2.dm
> +NOTE: It checks usr by default. Supply the "�" argument if you wish to check for a specific client/mob.
In default font it looks like a fucked up letter P, so not an issue

2022-02-25 23:22 UTC, drexample commented on code/modules/core_implant/cruciform/machinery/cruciformforge.dm
> +	var/tmp/obj/effect/flick_light_overlay/image_load
woudln't, all typepaths were replaced, not gonna edit because upstream

2022-02-25 23:23 UTC, drexample commented on code/modules/hivemind/machines.dm
> +			to_chat(H, SPAN_NOTICE("Reality flick_lights for a second, but you manage to focus!"))
![image](https://user-images.githubusercontent.com/19371983/155816204-e826c7d4-7b22-434c-b40f-e39e824872d7.png)

2022-02-26 03:47 UTC, EvilJackCarver commented on code/modules/core_implant/cruciform/machinery/cruciformforge.dm
> +	var/tmp/obj/effect/flick_light_overlay/image_load
I hope so.

2022-02-26 22:04 UTC, drexample commented on code/modules/projectiles/guns/projectile/automatic/c20r.dm
> +	desc = "A C-20M SMG frame. The syndicate's bread and butter, reverse-engineered."
It is a faction

2022-02-26 22:58 UTC, merged