Upstream merge
Eclipse-Station/NEV-Northern-Light pull request #1628
Opened 2022-03-19 14:23 UTC by drexample

## About The Pull Request

Decided not to delay too much and get 5000 merge conflicts

## Why It's Good For The Game

More content

## Changelog
:cl:
add: oopstrem merg
/:cl:

2022-03-19 15:12 UTC, EvilJackCarver requested changes

2022-03-19 15:12 UTC, EvilJackCarver commented on code/modules/economy/economy_misc.dm
> +	T.date = "2 April, 2339"
This date is still in the future - is this intentional?

2022-03-19 15:12 UTC, EvilJackCarver commented on code/modules/mob/living/carbon/human/human.dm
> +	to_chat(src, "<span class='notice'>You are now [dodging ? "dodging incoming fire" : "not dodging incoming fire"].</span>")
`to_chat(src, "<span class='notice'>You are [dodging ? "now dodging incoming fire" : "no longer dodging incoming fire"].</span>")`

would probably work better than "now dodging"/"now not dodging"

2022-03-19 15:12 UTC, EvilJackCarver commented on code/modules/mob/living/carbon/superior_animal/stalker/stalker.dm
> +// OneStar patrol borg that defends OneStar facilities
I can't comment on the files themselves due to limitations of GitHub, but in the `code/modules/mob/living/carbon/superior_animal/stalker/` directory, `ai.dm`, `attack.dm` and `life.dm` are empty files. Is this intentional?

2022-03-19 15:12 UTC, EvilJackCarver commented on code/modules/projectiles/ammunition/bullets.dm
> +	name = "AG FR \"Floodlight\""
Aster's Guild abbreviation

2022-03-19 15:12 UTC, EvilJackCarver commented on code/modules/projectiles/guns/energy/plasma.dm
> +            There\'s an inscription on the stock. \'For those whom the Angels hath cursed: thou wilt find, have no one to help.\'"
Oddly religious to be coming from NanoTrasen...

2022-04-15 19:28 UTC, drexample commented on code/modules/mob/living/carbon/superior_animal/stalker/stalker.dm
> +// OneStar patrol borg that defends OneStar facilities
apparently

2022-04-15 19:29 UTC, drexample commented on code/modules/projectiles/guns/energy/plasma.dm
> +            There\'s an inscription on the stock. \'For those whom the Angels hath cursed: thou wilt find, have no one to help.\'"
It's a donated weapon.

2022-04-15 21:52 UTC, EvilJackCarver requested changes
Just a couple missed NeoTheo references.

2022-04-15 21:52 UTC, EvilJackCarver commented on code/game/objects/items/weapons/design_disks/NeoTheology.dm
> +	disk_name = "NeoTheology Armory - \"Hastatii Arms\""
Missed two, here's the first...

2022-04-15 21:52 UTC, EvilJackCarver commented on code/game/objects/items/weapons/design_disks/NeoTheology.dm
> +	disk_name = "NeoTheology Armory - Purger Plasma Rifle"
...here's the second.

2022-04-15 22:02 UTC, EvilJackCarver approved these changes

2022-04-16 21:53 UTC, merged