Adds ", lockers," to the multitool description
Eclipse-Station/NEV-Northern-Light pull request #1637
Opened 2022-04-06 18:58 UTC by GuiltyNeko

## About The Pull Request
Title is a meme but the point is, multitools can pulse lockers to open them, it'd be good to make it visible that they can do such

## Why It's Good For The Game
Get players interacting with a not-entirely-known feature

## Changelog
I hate changelogs, and this is something you will quite literally see in-game anyways, and nobody reads changelogs, and also all the tags are way vague.

2022-04-12 15:15 UTC, EvilJackCarver submitted a review, later dismissed
Approved after code freeze lifts.

2022-04-16 22:22 UTC, drexample requested changes
Changelog bot runtimes if encountering empty changelog. 
Changelogs are mandatory for most contributions.

2022-04-22 00:52 UTC, GuiltyNeko commented
Oh, weh. That's annoying.

2022-04-22 21:18 UTC, EvilJackCarver approved these changes

2022-04-26 21:47 UTC, merged