WHATS UP FUCKERS
Eclipse-Station/NEV-Northern-Light pull request #1699
Opened 2023-02-14 10:05 UTC by MciReloaded

## About The Pull Request

Fixes #1632 
## Why It's Good For The Game

Allows borgs to speak in the proper channels without having to call the reset variable manually. 
## Changelog
:cl:
fix: #1632 Updates borg radio properly on creation of borg and changing of borg's type INSTEAD of whenever the hell it was doing it before.

/:cl:

2023-02-14 13:23 UTC, MciReloaded commented
I know, I see the problem. Will re-upload with the properly compiled version.

2023-02-21 19:29 UTC, EvilJackCarver requested changes
I'll leave it to Nestor to figure out whether the FILE_DIR definitions are necessary, since you're overwriting the definition over and over, but for now I've only got an untagged edit

2023-02-21 19:29 UTC, EvilJackCarver commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +		R.radio.recalculateChannels()*/
Untagged Eclipse edit

2023-03-15 08:16 UTC, MciReloaded commented
apologies on that, rookie mistake. I forgot to toggle that when I re-downloaded the repo.

2023-03-15 17:14 UTC, EvilJackCarver approved these changes

2023-03-16 20:13 UTC, merged