Helptext update, Phase 1
Eclipse-Station/NEV-Northern-Light pull request #1701
Opened 2023-03-13 07:51 UTC by EvilJackCarver

## About The Pull Request

Gets the bulk of the helptext update available for players.

Also includes a bugfix I forgot to throw in for the Maverick that I never got around to removing from this.

## Why It's Good For The Game

We don't use our helptext and fluff text examine code very much, if at all. Now we do.

## Changelog
:cl:
add: Helptext is in for a good chunk of items. To see the helptext, examine an item and look at your Examine tab.
fix: Fixes an issue where the Maverick's damage calculations could come out wrong.
/:cl:

2023-04-06 23:27 UTC, MciReloaded requested changes

2023-04-06 23:27 UTC, MciReloaded commented on code/modules/examine/descriptions/firearms.dm
> +	else if(one_hand_penalty)
There are a few guns that have issues firing with one hand that aren't energy- do we want to specify between energy and ballistic?

2023-04-06 23:27 UTC, MciReloaded commented on code/modules/examine/descriptions/machinery_nol.dm
> +	description_info = "A jukebox is used to play music. What music it contains is \
Maybe note that they can also take in music tapes?

2023-04-06 23:27 UTC, MciReloaded commented on code/modules/examine/descriptions/union.dm
> +	the surface of a planet, and has a range of 2 tiles (a 5×5 square) of the scan \
Maybe 2 tiles from the scan point?

2023-04-06 23:27 UTC, MciReloaded commented on code/modules/examine/descriptions/union.dm
> +	the surface of a planet, and has a range of 2 tiles (a 5×5 square) of the scan \
Also nonuniform numbering for tile distances- sometimes it's 2, other times two. Should likely stick to one for uniformity sake.

2023-04-07 08:48 UTC, EvilJackCarver commented on code/modules/examine/descriptions/atmospherics.dm
> +	Just be mindful of using it to phoronflood, as that could easily get you in trouble \
I'll change it to "Just be mindful of using it to flood an area with phoron, [...]"

2023-04-07 08:49 UTC, EvilJackCarver commented on code/modules/examine/descriptions/command.dm
> +
If you can think of any, please do let me know. I got nothin'.

2023-04-07 08:49 UTC, EvilJackCarver commented on code/modules/examine/descriptions/engineering.dm
> +	it unexpectedly shuts off while you're working nearby - if you can see it, you're \
Changed as written.

2023-04-07 08:50 UTC, EvilJackCarver commented on code/modules/examine/descriptions/consoles_and_computers.dm
> +	also control the thrust limiter and shut down thrusters with it."
Changed to "shut down the thrusters". 

The reason for the initial text is you can shut down *individual* thrusters as well as a global off/on, but "shut down the thrusters" reads better.

2023-04-07 08:50 UTC, EvilJackCarver commented on code/modules/examine/descriptions/__defines.dm
> +#define GENERIC_FLUFF_FIREARMS_NANOTRASEN "NanoTrasen has only recently expanded into the realm of small arms manufacturing, focusing primarily on energy weapons. However their very first pistol, the
Changed as requested.

2023-04-07 08:51 UTC, EvilJackCarver commented on code/modules/examine/descriptions/atmospherics.dm
> +	description_info = "Exhaust vents are essentially an opening where gas from \
Changed as requested.

2023-04-07 08:52 UTC, EvilJackCarver commented on code/modules/examine/descriptions/engineering.dm
> +
```C
// [...]
	"For most shield generators, the trip point for this is 125 Celsius, or about \
	398 Kelvin. Keep an ear on your radio for an overheat alarm. In the event it \
	overheats and shuts down, it will also set itself to only draw 1 kilowatt of \
	power, to prevent an infinite overheat loop."
```

Look OK?

2023-04-07 08:53 UTC, EvilJackCarver commented on code/modules/examine/descriptions/firearms.dm
> +	else if(one_hand_penalty)
The part you flagged is under `/obj/item/gun/energy`. The text for ballistics is further down, around line 135 or so.

2023-04-07 08:54 UTC, EvilJackCarver commented on code/modules/examine/descriptions/machinery_nol.dm
> +	description_info = "A jukebox is used to play music. What music it contains is \
```C
/obj/machinery/media/jukebox
	description_info = "A jukebox is used to play music. What music it contains is \
	entirely up to the server operator. \n\
	\n\
	If you wish, you can also load a music tape into a jukebox and have it play \
	from that."
```

Look OK?

2023-04-07 08:56 UTC, EvilJackCarver commented on code/modules/examine/descriptions/union.dm
> +	the surface of a planet, and has a range of 2 tiles (a 5×5 square) of the scan \
Changed as requested in both comments.

2023-04-07 21:09 UTC, MciReloaded requested changes

2023-04-07 21:09 UTC, MciReloaded commented on code/modules/examine/descriptions/command.dm
> +
The AI is a nigh-omnipresent force on the ship that makes it hard for you to get anywhere you're not supposed to. Using these modules, however, you may be able to bend these rules to suit you and your needs better.

2023-04-07 21:48 UTC, EvilJackCarver commented on code/modules/examine/descriptions/command.dm
> +
Changed as requested.

2023-04-07 22:05 UTC, MciReloaded approved these changes

2023-04-08 05:50 UTC, MciReloaded approved these changes

2023-04-08 06:04 UTC, merged