Sojourn Mob Port Part 1
Eclipse-Station/NEV-Northern-Light pull request #1703
Opened 2023-03-15 09:26 UTC by MciReloaded

## About The Pull Request
This pull request brings in a few of the more specialized spiders from Sojourn, as well as fixes a few issues with the nitro roach's files in the mob.dmi. 

## Why It's Good For The Game
Adds in some unique opportunities for players when fighting spiders, similar to roaches. Ensures that simply one weapon does not reign supreme in maintenance. Part one of the mob introduction project- don't want to overwhelm everyone with a bunch of new mobs all at once, as well as allowing me to make sure this project does not become out of hand fast.

## Changelog
:cl:
add: Shibireru Spider
add: Izumo Spider
add: Hakai Spider
add: Tsurai Spider
imageadd: added icons for the Shibireru, Izumo, Hakai, and Tsurai spiders. Other icons for porting consideration/part 2 are also ported and available for preview.

/:cl:

2023-03-15 17:23 UTC, EvilJackCarver requested changes
Need some screenshots of the sprites.

2023-03-15 17:23 UTC, EvilJackCarver commented on zzz_modular_eclipse/code/modules/mob/Spiceder.dm
> +	desc = "A massive tarrantula. This peculiar arachnid reeks of spicy peppers."
"tarantula"

2023-03-15 17:23 UTC, EvilJackCarver commented on zzz_modular_eclipse/code/modules/mob/Spiceder.dm
> +	gas_sac.add_reagent("condensedcapsaicin", 1)
You're gonna want to cap the amount it can hold for balancing purposes, otherwise a spider that's been alive since the start of the round 2 hours ago can fire this thing off 3600 times.

2023-03-15 17:23 UTC, EvilJackCarver commented on zzz_modular_eclipse/code/modules/mob/phoron.dm
> +	kerplode()
Do we really want another suicide mob? (See the hivemind drone)

2023-03-15 17:23 UTC, EvilJackCarver commented on icons/mob/human_races/cyberlimbs/onestar/one_star_main.dmi
Sprite changes outside of modular

2023-03-16 03:01 UTC, MciReloaded commented on zzz_modular_eclipse/code/modules/mob/Spiceder.dm
> +	desc = "A massive tarrantula. This peculiar arachnid reeks of spicy peppers."
Yes, I messed that up. Quick fix.

2023-03-16 03:02 UTC, MciReloaded commented on zzz_modular_eclipse/code/modules/mob/Spiceder.dm
> +	gas_sac.add_reagent("condensedcapsaicin", 1)
The gas sac is maxed out at 50, if I coded it correctly.

2023-03-16 03:02 UTC, MciReloaded commented on icons/mob/human_races/cyberlimbs/onestar/one_star_main.dmi
I have no idea how that managed to sneak into this branch- this was meant to be something else I was working on independently. will remove from this request.

2023-03-16 03:03 UTC, MciReloaded commented on zzz_modular_eclipse/code/modules/mob/phoron.dm
> +	kerplode()
This is how it was from Sojourn ported over nearly directly- if you have other ideas for the Phoron Spider, let me know and I can include it in the next push. Will be replaced with a different spider for this wave.

2023-03-16 05:36 UTC, MciReloaded commented on zzz_modular_eclipse/code/modules/mob/Spiceder.dm
> +	gas_sac.add_reagent("condensedcapsaicin", 1)
![image](https://user-images.githubusercontent.com/44788725/225524543-f575426d-30e9-4a01-8874-6c65e97d1a54.png)

2023-03-16 06:32 UTC, EvilJackCarver commented on zzz_modular_eclipse/code/modules/mob/Spiceder.dm
> +	gas_sac.add_reagent("condensedcapsaicin", 1)
I saw, but I didn't see any checks initially to ensure that the gas sac didn't go over 50 units. I'll look again.

2023-03-16 09:28 UTC, EvilJackCarver commented on zzz_modular_eclipse/code/modules/mob/Eris Spiders/taser.dm
> +	desc = "A massive tarrantula. This peculiar arachnid seems to have sparks across it's chitin. "
Don't know how I missed this, but "tarantula"

2023-03-16 09:32 UTC, EvilJackCarver approved these changes
Approved once the filenames are standardised

2023-03-16 20:14 UTC, merged