Project Jackboot
Eclipse-Station/NEV-Northern-Light pull request #1719
Opened 2023-05-12 04:56 UTC by Valanthe500

## About The Pull Request
This is the second Pull Request of Project Jackboot. In this we prepare everything needed for an introductory event (date TBD). This request specifically:
Introduces two new roles: The Lazarus Trauma Team, and the Xingyun Enforcer. Two security specialist roles, but outside of Aegis. These roles will have a limited scope at first, mainly being there to act as frontline responders to defend the high value areas of Medical and Engineering, while deferring to Aegis for issues outside their jurisdiction. 
Map changes: cells have been added in order to provide these roles an ability to contain problematic persons should Aegis be unable or unwilling to intervene.
Adds 5 new weapons manufactured by "Heaven's Mandate." the state-owned weapons manufacturer of the Tiandi armed forces:
- "Mao" a heavy laser pistol. In balance, sits slightly above the Spider Rose, but below the Captain's Laser / Serenity (Also added some potential sprites for future attachments, will work on that later)
- "Guan Yu" a weak but fast firing laser rifle, based on the venerable Cog. It takes a significant damage hit in order to fire faster, and with much higher cell efficiency.
- "Huang Di" a carbine used by Tiandi civil defense forces, a good civilian alternative to the wintermute. Uses .20 rifle, but is semi automatic only, with a fixed internal magazine that needs to be hand loaded (a .20 speedloader is on my "add it later" list)
- "Yan" A terrifying chemical grenade as dangerous to its user as it is to its targets (It's a polyacid grenade, which sounds scary, and it is, unarmoured hits can deal upwards of 150 burn, however it is very unreliable, with damage varying wildly even across mobs within the same blast. I put it at about as deadly as the blast grenades.)
- "Dadao" A heavy broadsword issued to Tiandi officers. Brutal and effective. (effectively a reskinned officer's saber, not much to add about this one)

And as a bonus:
- added 4 boxes of sting rounds to the Aegis Armoury (fixes #1713 )
- re-added the practice lasers to the shooting ranges, was unable to replicate the reported issue and they worked fine in local testing (fixes #1705 )
## Why It's Good For The Game

## Changelog
:cl:
add: Added Xingyun Enforcer
add: Added Lazarus Trauma Team (replaces paramedic)
add: Added 5 new weapons from "Heaven's Mandate"
/:cl:

2023-05-12 09:59 UTC, EvilJackCarver requested changes
first pass, at 4 AM

also, if you want your gun to have custom fluff text for the company, define it in `/code/modules/examine/descriptions/__defines.dm` and set the heaven's mandate weapons' `description_fluff` to that define

2023-05-12 09:59 UTC, EvilJackCarver commented on code/datums/outfits/jobs/medical.dm
> +	backpack_contents = list(/obj/item/gun/projectile/selfload/moebius = 1, /obj/item/ammo_magazine/pistol/rubber = 2, /obj/item/modular_computer/tablet/moebius/preset = 1, /obj/item/storage/firstaid/ad
unflagged edit

2023-05-12 09:59 UTC, EvilJackCarver commented on code/game/jobs/job/medical.dm
> +	<br>\
unflagged edits; given how extensive the editing in this file is, may be better to just put a note at the top to the effect of `//extensive eclipse edits in this file` or make the overrides in modular

2023-05-12 22:11 UTC, Valanthe500 commented on code/game/jobs/job/medical.dm
> +	<br>\
Hm, I don't recall editing this section. looks like I just deleted some empty lines. Either way I'll mark the edit. But yeah, now that you mention it, having the Trauma Team / Enforcer moved to Modular files might be a better idea. I'll see if I can get that working and update.

2023-05-12 22:17 UTC, EvilJackCarver commented on code/game/jobs/job/medical.dm
> +	<br>\
In the case of lines 95-97, looking back (at a decent hour!) it looks like it's whitespace edits in the form of indentation - you're good to leave these in unflagged. As for the other edits, though, please either

 - flag them individually
 - add a note at the top that there's extensive edits in the file, or
 - copy it to modular and do the overrides there

just bear in mind that byond doesn't like duplicate proc definitions (see below)

---

```c
/obj/example/proc/do_stuff()
    //...

/obj/example/proc/do_stuff()
    //...
```
the above will make the compiler shit its fuck

```c
/obj/example/proc/do_stuff()
    //...
/obj/example/do_stuff()
    //...
```

the compiler will accept that one

2023-05-12 22:56 UTC, EvilJackCarver requested changes

2023-05-12 22:56 UTC, EvilJackCarver commented on zzz_modular_eclipse/code/game/jobs/job/medical.dm
> +	Your primary role is that of a security officer for Lazarus. You make sure that the medical and science departmetns remain safe by ensuring people don't trespass or steal items and remove those who
```suggestion
	Your primary role is that of a security officer for Lazarus. You make sure that the medical and science departments remain safe by ensuring people don't trespass or steal items and remove those who shouldn't be there, by force if necessary.<br>\
```

Typo in "departments".

2023-05-12 22:56 UTC, EvilJackCarver commented on zzz_modular_eclipse/code/game/jobs/job/engineering.dm
> +	As a Xingyun employee, you were trained as an engineer first, and should have at least a passing familiarity with the basic functions that your department is expected to maintain, but if a specializ
```suggestion
	As a Xingyun employee, you were trained as an engineer, and should have at least a passing familiarity with the basic functions that your department is expected to maintain, but if a specialized engineer is available,  you should defer to them, as your primary duty is security.<br>\
```

Creates an implicit self-contradiction - "You were trained as an engineer first and foremost. Your duty, first and foremost, is security."

2023-05-12 22:56 UTC, EvilJackCarver commented on zzz_modular_eclipse/code/game/jobs/job/medical.dm
> +	Your secondary responsibility is that of an enforcer. Actions that require in house enforcement such as aiding doctors and security with violent patients in medical, securing the virology lab during
```suggestion
	Your secondary responsibility is that of an enforcer. Actions that require in house enforcement - such as aiding doctors and security with violent patients in medical, securing the virology lab during an outbreak, and aiding in the destruction of escaped slimes or experiments from science - fall on your shoulders.<br>\
```

Fragmented sentence.

2023-05-12 22:56 UTC, EvilJackCarver commented on zzz_modular_eclipse/code/game/jobs/job/medical.dm
> +	Your third duty is to aid medical doctors and act as a paramedic. Fixing and collecting patients, this can include retrieving chemicals, doing basic triage, and going out into maintenance recover th
Fragmented sentence. 

"Fixing and collecting patients, this can include retrieving chemicals, doing basic triage [...]" also doesn't read well.

2023-05-12 22:56 UTC, EvilJackCarver commented on zzz_modular_eclipse/code/game/jobs/job/medical.dm
> +		Ensure that any outbreaks are contained, such as slimes, infected monkeys, or kudzu."
Inconsistent - the Xingyun duties are a bulleted list, the Enforcer is a list without bullets.

2023-05-12 22:56 UTC, EvilJackCarver commented on zzz_modular_eclipse/code/game/jobs/job/medical.dm
> +	loyalties = "As a security specialist aboard the Northern Light, your first and only loyalty is to the Lazarus Foundation, protect their staff to the best of your ability, and follow their instructi
```suggestion
	loyalties = "As a security specialist aboard the Northern Light, your first and only loyalty is to the Lazarus Foundation. Protect their staff to the best of your ability, and follow their instructions and policies."
```

Bit of a run-on sentence there.

2023-05-12 23:27 UTC, Valanthe500 commented on zzz_modular_eclipse/code/game/jobs/job/medical.dm
> +	Your third duty is to aid medical doctors and act as a paramedic. Fixing and collecting patients, this can include retrieving chemicals, doing basic triage, and going out into maintenance recover th
This is what I get for copy-pasting fluff without proofreading properly.

2023-05-13 01:24 UTC, EvilJackCarver commented on zzz_modular_eclipse/code/game/jobs/job/medical.dm
> +	Your primary role is that of a security officer for Lazarus. You make sure that the medical and science departmetns remain safe by ensuring people don't trespass or steal items and remove those who
Regression

2023-05-13 01:24 UTC, EvilJackCarver commented on zzz_modular_eclipse/code/game/jobs/job/medical.dm
> +	Your secondary responsibility is that of an enforcer. Actions that require in house enforcement such as aiding doctors and security with violent patients in medical, securing the virology lab during
Regression

2023-05-13 01:35 UTC, EvilJackCarver approved these changes

2023-05-13 03:26 UTC, merged