Small map / bug fixes
Eclipse-Station/NEV-Northern-Light pull request #1725
Opened 2023-05-18 23:10 UTC by Valanthe500

## About The Pull Request
As there's still no sign of Nestor giving us what's needed for the upstream merge despite my constant badgering, figured I might as well get a bit of work done:

- Removes floating holo-posters in cryo area
![image](https://github.com/Eclipse-Station/NEV-Northern-Light/assets/23348904/2d3f2cff-d2a5-4c48-88a7-9104d004a299)
![image](https://github.com/Eclipse-Station/NEV-Northern-Light/assets/23348904/2db52e0e-a868-415d-b14f-1351b5ac967e)

- moves intercoms away from cryotubes / beds (this prevents a bug where spawning in will equip nearby intercoms into your suit storage)

- adds cleaning lockers that have simple cleaning supplies, to ease the mess with no custodians (fixes #1724)
![image](https://github.com/Eclipse-Station/NEV-Northern-Light/assets/23348904/8a18489f-7576-4e08-8fad-777784ef80cc)

- adds cable knots under the shield generators in the Engineering entrance, allowing them to be used without having to tear up floorboards. (Also unmodified the vars in those gens to make it so Engineering could use them, they required Laz access for some reason?)
![image](https://github.com/Eclipse-Station/NEV-Northern-Light/assets/23348904/cabca92e-be6d-4356-b44b-60d56dbbace7)

- Fixes #1707  Neohongo now mapped to "n"

- Fixes #1612 Set Teleporter access button req_access to 17- Teleporter (now same access as airlock into room)

- Removed a whole bunch of lights in maintenance to darken it, save power (seriously, one of the maint sections in engineering was using 3,000W just on lighting), and better delineate the "habited" areas of the ship from the "uninhabited."
![image](https://github.com/Eclipse-Station/NEV-Northern-Light/assets/23348904/35d9703c-e03e-4bc0-a271-b844cccd074b)
![image](https://github.com/Eclipse-Station/NEV-Northern-Light/assets/23348904/95241861-b138-4699-8063-b890e65b0803)

- Re-arranged the disposal pipe section near the Biogenerator (one pipe was overlapping another, something that doesn't happen anywhere else on the ship)
![image](https://github.com/Eclipse-Station/NEV-Northern-Light/assets/23348904/05d0fe01-c5af-4e22-9647-686af30a5563)
![image](https://github.com/Eclipse-Station/NEV-Northern-Light/assets/23348904/e0b165c3-8b40-43f7-8823-ad855c473144)

- Adds a disposal chute to the First Section Disposals area (near Perma) - allows trash to be sent to normal disposals if desired.
![image](https://github.com/Eclipse-Station/NEV-Northern-Light/assets/23348904/9e0cdfa8-78f3-46c3-ad07-55458a837acb)
The disposal unit
![image](https://github.com/Eclipse-Station/NEV-Northern-Light/assets/23348904/523dc8e3-c1a0-4249-b373-6b4c26c56ae5)
A little EVA jump to help discourage careless use.
## Why It's Good For The Game
These are just a series of small bugfixes and some map adjustments based on community feedback. Plus an addition of my own (the disposal chute) 

## Changelog
:cl:
add: Added new janitorial closets
add: added a new disposal chute from security disposals into the main disposal line.
del: Removed a bunch of lights from maintenance, 
fix: fixes Neohongo - now mapped to "n"
/:cl:

2023-05-18 23:13 UTC, EvilJackCarver commented on zzz_modular_eclipse/code/game/objects/structures/crates_lockers/closets/utility_closets.dm
> +	name = "\improper Janitorial closet"
Why is this capitalised? That'll make it say "This is a Janitorial closet"...

2023-05-18 23:17 UTC, Valanthe500 commented on zzz_modular_eclipse/code/game/objects/structures/crates_lockers/closets/utility_closets.dm
> +	name = "\improper Janitorial closet"
I'm gonna blame habit on that

2023-05-18 23:18 UTC, EvilJackCarver commented on zzz_modular_eclipse/code/game/objects/structures/crates_lockers/closets/utility_closets.dm
> +	name = "\improper Janitorial closet"
DANGIT BOBBEH

HOW MANY TIMES 'V I GOT TA TELL YOU ABOUT PROPANE AND PROPANE ACCESSORIES

2023-05-18 23:20 UTC, EvilJackCarver requested changes

2023-05-18 23:20 UTC, EvilJackCarver commented on maps/CEVEris/_CEV_Erida.dmm
You have a merge conflict somewhere in this file. Check your git tools; I can't resolve it from GitHub.

2023-05-19 00:59 UTC, Valanthe500 commented on maps/CEVEris/_CEV_Erida.dmm
I have no idea what or how I broke the map so completely.

It's fixed now, I hope, I tested it locally and nothing is exploding anymore.

2023-05-19 01:19 UTC, EvilJackCarver commented
Seeing some possible corruption here. I'm still looking.

![image](https://github.com/Eclipse-Station/NEV-Northern-Light/assets/1784490/41d8be0e-162b-4a2e-900a-917a21f9d1af)

2023-05-19 01:27 UTC, EvilJackCarver commented
Finished checking, that's the only odd thing that stood out to me.

2023-05-19 02:09 UTC, Valanthe500 commented
Yeah missed that one, forgot to look under the roach spawner, fixed now.

I did another once over of that area again, think I got everything now.

2023-05-19 03:17 UTC, EvilJackCarver approved these changes

2023-05-19 03:17 UTC, merged