Upstream merge
Eclipse-Station/NEV-Northern-Light pull request #1728
Opened 2023-05-19 11:32 UTC by drexample

## About The Pull Request

## Why It's Good For The Game

2023-05-19 12:12 UTC, EvilJackCarver requested changes
these notes are more for myself, really

i said i was going to fix it up after you got everything merged proper, and i stand by my word

2023-05-19 12:12 UTC, EvilJackCarver commented on code/datums/autolathe/guns.dm
> +	name = "Excelsior Car .30 Kalashnikov"
CAR is not standardised; revert to AR

2023-05-19 12:12 UTC, EvilJackCarver commented on code/datums/craft/recipes/guns.dm
> +	name = "HM LG \"Retina Burn\""
LR, laser rifle

2023-05-19 12:12 UTC, EvilJackCarver commented on code/datums/craft/recipes/guns.dm
> +	name = "HM LG \"Scorcher\""
LHG, laser handgun

2023-05-19 12:12 UTC, EvilJackCarver commented on code/datums/craft/recipes/guns.dm
> +	name = "HM Disco Vazer \"Lasblender\""
LSMG, laser SMG

2023-05-19 12:12 UTC, EvilJackCarver commented on code/datums/craft/recipes/guns.dm
> +	name = "HM AR \"Sermak\""
re-add calibre info

2023-05-19 12:12 UTC, EvilJackCarver commented on code/datums/outfits/jobs/medical.dm
> +	name = OUTFIT_JOB_NAME("Moebius Bio-Engineer")
moebius → laz

2023-05-19 12:12 UTC, EvilJackCarver commented on code/datums/outfits/jobs/science.dm
> +	name = OUTFIT_JOB_NAME("Moebius Psychiatrist")
moebius → laz, but don't we already have a psychiatrist define?

2023-05-19 12:12 UTC, EvilJackCarver commented on code/datums/perks/fate.dm
> +	W.name = "[W] of [holder.last_name]"
holder.family_name; we re-worked it a long time ago because it fucks with single-barrel names

2023-05-19 20:35 UTC, EvilJackCarver requested changes
20%

again, these notes are mostly for me

2023-05-19 20:35 UTC, EvilJackCarver commented on code/game/objects/items/weapons/design_disks/moebius.dm
> +	disk_name = "Moebius Scientifica - Genetics"
moebius here and below

2023-05-19 20:35 UTC, EvilJackCarver commented on code/game/objects/items/weapons/storage/deferred.dm
> +	desc = "A crate containing 4 bojevic autoshotguns and 120 rounds of .50 buck and slug ammunition each. good to keep handy \
Bojevic shotguns

2023-05-19 20:35 UTC, EvilJackCarver commented on code/game/objects/items/weapons/tools/tape.dm
> +	description_antag = "Can be used to make makeshift mouthwraps and to tape cameras silently"
makeshift gags, disable cameras "silently"

2023-05-19 20:35 UTC, EvilJackCarver commented on code/game/objects/landmarks/general.dm
> +	new /obj/item/paper(get_turf(src), text, "IH Armoury log")
ironhammer, uk variant spelling

2023-05-19 20:35 UTC, EvilJackCarver commented on code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
> +	name = "moebius psychiartist's locker"
moebius

2023-05-19 20:35 UTC, EvilJackCarver commented on code/game/objects/structures/signs.dm
> +	name = "Moebius Laboratories Sign"
moebius

2023-05-19 20:35 UTC, EvilJackCarver commented on code/game/objects/structures/window.dm
>  	var/proj_damage = Proj.get_structure_damage()
lint

2023-05-20 10:09 UTC, EvilJackCarver commented on code/game/area/Space Station 13 areas.dm
> +
also fucken make sure it's merged properly because val put his blood sweat and tears into that

2023-05-20 11:34 UTC, EvilJackCarver requested changes
1062/2959

2023-05-20 11:34 UTC, EvilJackCarver commented on code/modules/genetics/nano_module.dm
> +	extended_desc = "Copyright © 2563, Moebius Laboratories. All rights reserved."
moebius

2023-05-20 11:34 UTC, EvilJackCarver commented on code/modules/hivemind/machines.dm
> +	new gift(get_turf(loc))
lint

2023-05-20 11:34 UTC, EvilJackCarver commented on code/modules/holodeck/HolodeckControl.dm
> +		holo_obj.plane = 63 //This makes all objects load on the plane that Eris's 3rd z-level uses for objects. This is not dynamic.
verify z-level and update

2023-05-20 11:34 UTC, EvilJackCarver commented on code/modules/holodeck/HolodeckControl.dm
> +	"Industrial Arenas"		= "industrial_arena"
holodeck areas.

2023-05-20 11:34 UTC, EvilJackCarver commented on code/modules/holodeck/HolodeckPrograms.dm
> +	"turnoff" 			= new/datum/holodeck_program(/area/holodeck/source/off)
holodeck areas

2023-05-20 11:34 UTC, EvilJackCarver commented on code/modules/integrated/README.md
given that integrated circuits are removed so extensively, may as well just rid ourselves of them; nobody used them anyway

2023-05-20 11:34 UTC, EvilJackCarver commented on code/modules/mechs/interface/screen_objects.dm
> +				usr.show_message(SPAN_NOTICE("Your suit's safe operating limit ceiling is [(celsius ? "[owner.material.melting_point - T0C] °C" : "[owner.material.melting_point] K" )]."))
safe operating temperature ceiling; this is clunky

2023-05-20 11:34 UTC, EvilJackCarver commented on code/modules/mining/ore_datum.dm
> +	name = ORE_PLASMA
ensure there's no plasma/phoron regressions here

2023-05-20 11:34 UTC, EvilJackCarver commented on code/modules/mob/holder.dm
> +	desc = "An important cat, straight from Hansa."
lore regression

2023-05-20 11:34 UTC, EvilJackCarver commented on code/modules/mob/living/carbon/human/human.dm
> +		to_chat(src, SPAN_NOTICE("You begin to phaze trough \the [bingo]"))
typo, should be phase

2023-05-20 11:34 UTC, EvilJackCarver commented on code/modules/mob/living/carbon/human/human.dm
> +	to_chat(src, SPAN_NOTICE("You are now [holding_back ? "holding back your attacks" : "not holding back your attacks"]."))
revert to "pull punches" because "Hold your attacks back" is clunky for a verb name; also rewrite to_chat span - "you are now not holding back your attacks" is clunky af

2023-05-20 11:34 UTC, EvilJackCarver commented on code/modules/mob/living/carbon/human/human_organs.dm
> +				drop_from_inventory(E)
lint

2023-05-20 11:34 UTC, EvilJackCarver commented on code/modules/mob/living/carbon/human/species/species.dm
lint

2023-05-20 11:34 UTC, EvilJackCarver commented on code/modules/mob/living/carbon/human/species/station/slime.dm
> +	name = SPECIES_SLIME
re-check defines for this

2023-05-20 11:34 UTC, EvilJackCarver commented on code/modules/mob/living/carbon/slime/items.dm
references to plasma as a material throughout

2023-05-20 11:34 UTC, EvilJackCarver commented on code/modules/mob/living/carbon/slime/powers.dm
lints

2023-05-21 03:03 UTC, EvilJackCarver requested changes
1379/2959

2023-05-21 03:03 UTC, EvilJackCarver commented on code/modules/projectiles/guns/projectile/shotgun/handmade.dm
> +	name = "Ponyets frame"
\improper

2023-05-21 03:03 UTC, EvilJackCarver commented on code/modules/projectiles/guns/projectile/shotgun/handmade.dm
add name: HM SG "Ponyets"

2023-05-21 03:03 UTC, EvilJackCarver commented on code/modules/projectiles/guns/projectile/shotgun/ks23.dm
> +	name = "Excelsior SG KS-23"
EX for Excelsior, \improper

2023-05-21 03:03 UTC, EvilJackCarver commented on code/modules/projectiles/guns/projectile/shotgun/ks23.dm
> +	serial_type = "Excelsior"
Abbreviate?

2023-05-21 03:03 UTC, EvilJackCarver commented on code/modules/projectiles/guns/projectile/shotgun/regulator.dm
> +	name = "NT SG \"Regulator M1000\""
\improper

2023-05-21 03:03 UTC, EvilJackCarver commented on code/modules/projectiles/guns/projectile/shotgun/type21.dm
> +	name = "OS Type 21 SG \"Yaoguai\"" //Demon
\improper, fix standardised formatting

2023-05-24 07:05 UTC, EvilJackCarver requested changes
github is bugging out, so i'm stopping here

1614/2959

2023-05-24 07:05 UTC, EvilJackCarver commented on code/modules/trade/datums/trade_stations_presets/1-common/nt_cruisers.dm
> +		"Neotheology Cells" = list(
neotheo

2023-05-24 07:05 UTC, EvilJackCarver commented on code/modules/trade/datums/trade_stations_presets/1-common/nt_cruisers.dm
> +		/obj/item/computer_hardware/hard_drive/portable/design/nt/triarii = offer_data("NeoTheology Armory - \"Triarii Arms\"", 8000, 1)
neotheo

2023-05-24 07:05 UTC, EvilJackCarver commented on code/modules/trade/datums/trade_stations_presets/1-common/smoke.dm
> +		"FTB \'Costaguana\'" = "Free Trade Beacon \'Costaguana\': \"Bienvenidos, weary travelers. Collect your mind while you inhale the finest synthetic tobacco in Hanza space.\"",
FTU Beacon, probably nix the Hanza space since it sounds like we're not in nullspace

2023-05-24 07:05 UTC, EvilJackCarver commented on code/modules/trade/datums/trade_stations_presets/1-common/zarya.dm
> +			/obj/item/computer_hardware/hard_drive/portable/design/conveyors = good_data("Technomancers LAT-018 Logistics", list(5, 10), 300)
technomancer

2023-05-24 07:05 UTC, EvilJackCarver commented on code/modules/trade/datums/trade_stations_presets/2-uncommon/botany.dm
> +		"MTV \'Arbor\'" = "Moebius Trade Vessel \'Arbor\': Connection with the Moebius botanical research network established."
moebius

2023-05-24 07:42 UTC, EvilJackCarver requested changes
we've hit the point where i'm just clicking 'viewed' on icons and sounds (and tgui stuff because i can't really be arsed to thumb through TGUI)

2169/2959

2023-05-24 07:42 UTC, EvilJackCarver commented on code/modules/trade/datums/trade_stations_presets/2-uncommon/rigprovider.dm
> +		"ATB \'Boris\'" = "Aster\'s Trade Beacon \'Boris\': \"Hello there, we are hardsuit salvagers. We will be around the system for some time and we have leftover stock. We can sell some off if you want
Aster's

2023-05-24 07:42 UTC, EvilJackCarver commented on code/modules/trade/datums/trade_stations_presets/2-uncommon/rigprovider.dm
> +		/obj/item/rig/combat/ironhammer = offer_data("Ironhammer hardsuit control module", 8000, 1),
lore compliance

2023-05-24 07:42 UTC, EvilJackCarver commented on code/modules/trade/datums/trade_stations_presets/2-uncommon/stylestation.dm
> +		/obj/item/clothing/head/armor/faceshield/paramedic = offer_data("Moebius paramedic helmet", 1000, 1),
lore compliance

2023-05-24 17:34 UTC, EvilJackCarver requested changes
finished reviewing. 

though i'll be honest i didn't look at sprites, sounds, or anything tgui related.

2023-06-06 08:46 UTC, Valanthe500 commented on code/controllers/subsystems/voting/poll.dm
> +	var/question = "Voting, voting, candidates are пичке!"
My limited ability to translate Russian (Google) is failing me, best I can find is it seems to be a name?
I'm assuming this is some Russian meme, I'm gonna change it to "dumb."

2023-06-06 08:52 UTC, MciReloaded commented on code/controllers/subsystems/voting/poll.dm
> +	var/question = "Voting, voting, candidates are пичке!"
The one I'm pulling is Serbian for 'pussy', so assuming pussies.

2023-06-06 09:14 UTC, Valanthe500 commented on code/datums/setup_option/backgrounds/origin.dm
> -	restricted_depts = ENGINEERING | MEDICAL | SCIENCE | CHURCH | GUILD | CIVILIAN | SERVICE
Lore Team - Engaged!

2023-06-06 09:23 UTC, Valanthe500 commented on code/game/antagonist/station/inquisitor.dm
> +	to_chat(player, "You will need a ritual book to utilise your abilities. They can be found or purchased in the chapel. The Bounty ritual can be used to request items from New Rome. You may request a
Will change "New Rome" to "The Council" - we don't have lore about any "home base" the Mekhanites are actually based out of.

2023-06-06 09:29 UTC, Valanthe500 commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +					LANGUAGE_LATIN = 0,
Yeah, I'm gonna revert this, it is removing the ability for robots to understand any alien language.

2023-06-06 09:54 UTC, Valanthe500 commented on code/game/objects/items/weapons/cards_ids.dm
> +	description_antag = "This item has 10 by default. Emagging turrets turns them lethal to everyone. Emagging a door opens it and bolts it. Emagging a non-sentient robot turns them hostile. Emagging a
I'm gonna go with "uses"

2023-06-06 10:10 UTC, Valanthe500 commented on code/modules/power/cell.dm
> +	description_antag = "Can be inserted with plasma to make it blow whenever power is being pulled."
Fixed.

2023-06-06 10:16 UTC, Valanthe500 commented on code/modules/power/smes.dm
> +	description_antag = "Cutting the safety wire lets you insert SMES components when its charged, doing so will create a preety big blast"
Fixed.

2023-06-06 20:06 UTC, Valanthe500 commented on code/modules/projectiles/gun.dm
> +			user.visible_message(SPAN_NOTICE("[user] begins scribbling \the [name]'s gun serial number away."), SPAN_NOTICE("You begin removing the serial number from \the [name]."))
What tool do you think we should use here? I know in real life you'd use a file / grinder, but we don't have those. I'm leaning towards screwdriving, based on the visible message there "[user] begins scribbling..."

2023-06-07 02:19 UTC, Sly9sky commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +					LANGUAGE_LATIN = 0,
I should perhaps note here my experience with this. The current state of this upstream is that robots only hear gibberish if they get a module reset. Seems to be relatively fine otherwise.

Pretty much what Val said, these lines do remove the ability to understand language.

2023-06-07 08:54 UTC, Valanthe500 commented on code/modules/core_implant/cruciform/cruciform.dm
> +				wearer.visible_message(SPAN_NOTICE("<b>\The [AM]</b> rips through \the [wearer]'s flesh."), SPAN_NOTICE("<b>\The [AM]</b> rips through your flesh. Your [I.name] hurts."))
This whole section is the proc for cruciforms forcibly removing augmentations / implants etc. I'm gonna comment this out, as ours shouldn't be removing those, and I assume that goes for the new genemods / augmented organs as well.

Hoping I can get away with just killing this code and it won't break anything further on.

2023-06-07 08:59 UTC, Valanthe500 commented on code/modules/mechs/interface/screen_objects.dm
> +				usr.show_message(SPAN_NOTICE("Your suit's safe operating limit ceiling is [(celsius ? "[owner.material.melting_point - T0C] °C" : "[owner.material.melting_point] K" )]."))
Changed to: "Your suit's maximum safe operating temperature is..."

2023-06-07 09:14 UTC, Valanthe500 commented on code/modules/mining/ore_datum.dm
> +	name = ORE_PLASMA
Looked into this, it seems to be fine. the name var wants a define and the define is correct compared to other files and the defines for phoron. 

This may actually be fixing an issue that was only recently reported to me about phoron ore only being minable through deep drilling. Not something I'm going to invest time into investigating right now, just an observation, but worth keeping in mind if the issue (assuming it is one and wasn't intentional) persists after the merge.

2023-06-07 09:23 UTC, Valanthe500 commented on code/modules/mob/living/carbon/human/species/station/slime.dm
> +	name = SPECIES_SLIME
Will need to leave this one for you / Nestor, I can't make heads or tails of it.
I can't find SPECIES_SLIME defined anywhere else. and looking at other species datums, some have defines like that, others are "text' entries, and I can't figure out which it's actually supposed to be.

2023-06-07 09:38 UTC, Valanthe500 commented on code/modules/projectiles/guns/energy/crossbow.dm
> +	serial_type = "S"
Fixed

2023-06-07 09:38 UTC, Valanthe500 commented on code/modules/projectiles/guns/energy/crossbow.dm
> +	serial_type = "NT"
fixed

2023-06-07 09:39 UTC, Valanthe500 commented on code/modules/projectiles/guns/energy/decloner.dm
> +	serial_type = "ML" // Moebius
fixed

2023-06-07 09:40 UTC, Valanthe500 commented on code/modules/projectiles/guns/energy/floragun.dm
> +	serial_type = "ML"
fixed

2023-06-07 09:41 UTC, Valanthe500 commented on code/modules/projectiles/guns/energy/laser.dm
> +	serial_type = "ML"
fixed

2023-06-07 09:41 UTC, Valanthe500 commented on code/modules/projectiles/guns/energy/laser.dm
> +	serial_type = "ML"
fixed

2023-06-07 09:44 UTC, Valanthe500 commented on code/modules/projectiles/guns/energy/laser.dm
> +	name = "HM LG \"Scorcher\""
Changed to "HM LR M \"Retina Burn\"" to comply with our standardized gun names.

2023-06-07 09:57 UTC, Valanthe500 commented on code/modules/projectiles/guns/energy/laser.dm
> +	name = "HM LG \"Retina Burn\""
Whoops, responded to the wrong comment at first. Changed to "HM LCAR M \"Retina Burn\"" to comply with our standardized gun names.

2023-06-07 17:22 UTC, EvilJackCarver commented on code/modules/mob/living/carbon/human/species/station/slime.dm
> +	name = SPECIES_SLIME
probably best to revert it then

2023-06-07 17:24 UTC, EvilJackCarver commented on code/modules/power/apc.dm
> +	description_antag = "Can be unlocked by pulsing the lock wire. Can also be saboutaged by inserting plasma into its cell, making it blow whenever its turned on"
all my work with helptext was under /modules/examine; if it's defined there, then this almost certainly overrides this due to file loading order

2023-06-07 17:25 UTC, EvilJackCarver commented on code/modules/projectiles/gun.dm
> +			user.visible_message(SPAN_NOTICE("[user] begins scribbling \the [name]'s gun serial number away."), SPAN_NOTICE("You begin removing the serial number from \the [name]."))
problem is, screwdrivers are used to remove mods you've installed. 

a knife maybe? it's not good for the blade, but it would make sense to scratch out the serial

2023-06-07 22:11 UTC, MciReloaded commented
Set it so you have to use a knife set to harm.

On Wed, Jun 7, 2023, 6:05 PM Valanthe500 ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In code/modules/projectiles/gun.dm
> <https://github.com/Eclipse-Station/NEV-Northern-Light/pull/1728#discussion_r1222221461>
> :
>
> >  /obj/item/gun/attackby(obj/item/I, mob/living/user, params)
> -	if(!istool(I) || user.a_intent != I_HURT)
> +	var/tool_type = I.get_tool_type(user, list(QUALITY_BOLT_TURNING, serial_type ? QUALITY_HAMMERING : null), src)
> +	switch(tool_type)
> +		if(QUALITY_HAMMERING)
> +			user.visible_message(SPAN_NOTICE("[user] begins scribbling \the [name]'s gun serial number away."), SPAN_NOTICE("You begin removing the serial number from \the [name]."))
>
> That could work, but will create a conflict with the tacknife, as it's
> also a weapon mod (becomes a bayonet when applied to a firearm).
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Eclipse-Station/NEV-Northern-Light/pull/1728#discussion_r1222221461>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKVWX5PFD55HKPKSCBSGLITXKD3JZANCNFSM6AAAAAAYHVGIJQ>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***
> com>
>

2023-06-07 22:17 UTC, MciReloaded commented on code/modules/projectiles/gun.dm
> +			user.visible_message(SPAN_NOTICE("[user] begins scribbling \the [name]'s gun serial number away."), SPAN_NOTICE("You begin removing the serial number from \the [name]."))
Set a screwdriver or knife to harm to take it off instead of doing it whenever. We have intent verbs, we may as well use them

2023-06-07 23:55 UTC, Valanthe500 commented on code/modules/mob/living/carbon/human/species/station/slime.dm
> +	name = SPECIES_SLIME
On a hunch, I had a try at compiling the code to see if I could sort through some of the errors, and I noticed "SPECIES_SLIME" comes up like a dozen times as "Undefined var." I wanted to confirm that "Promethean" is what I should revert them all to, but every time I try to load up the changed files, Chrome lights my RAM on fire and crashes the browser...

So I reverted all instances of "SPECIES_SLIME" to "Promethean" and when I compile, I'm not getting errors on those lines anymore, so improvement, maybe?

2023-06-08 06:48 UTC, Valanthe500 commented on code/modules/text_to_speech/tts_main.dm
> +
Did "NT to NanoTrasen," "LF to Lazarus Foundation," and "FT to Free Trade Union" (I don't really wanna fight with it to make it listen for 3 characters right now, It's something we can come back to at a later date if needed.)

2023-06-10 09:30 UTC, EvilJackCarver commented on code/modules/projectiles/gun.dm
> +			user.visible_message(SPAN_NOTICE("[user] begins scribbling \the [name]'s gun serial number away."), SPAN_NOTICE("You begin removing the serial number from \the [name]."))
i'd say we go with mci's idea here.

2023-11-10 22:55 UTC, EvilJackCarver reviewed
Ready for testmerge.

2023-11-23 06:53 UTC, benj8560 commented
Was goobering around with this on a private server. Noticed that the Laz cloner is just making slabs of meat rather then bodies.

2023-12-05 09:49 UTC, EvilJackCarver reviewed
...I've been away on holiday for like a week. Jog my memory - why are we changing switch statements to daisy-chained if-else statements?

2023-12-05 12:51 UTC, drexample commented
> ...I've been away on holiday for like a week. Jog my memory - why are we changing switch statements to daisy-chained if-else statements?

Believe it or not, data handling in switch statements have been changes in 515 and now they accept only constants in them.

2023-12-05 18:51 UTC, EvilJackCarver commented
> > ...I've been away on holiday for like a week. Jog my memory - why are we changing switch statements to daisy-chained if-else statements?
> 
> Believe it or not, data handling in switch statements has been changed in 515 and now they accept only constants in them.

...Understandable.

Proceed with test merge.

2024-06-25 03:59 UTC, merged